//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class USAePayAddress;
@class USAePayCheckData;
@class USAePayCreditCardData;
@class USAePayFieldValueArray;
@class USAePayTransactionDetail;
@class USAePayLineItemArray;
@class USAePayRecurringBilling;
#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayTransactionRequestObject : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getAccountHolder) NSString* AccountHolder;

@property (retain,nonatomic,getter=getAuthCode) NSString* AuthCode;

@property (retain,nonatomic,getter=getBillingAddress) USAePayAddress* BillingAddress;

@property (retain,nonatomic,getter=getCheckData) USAePayCheckData* CheckData;

@property (retain,nonatomic,getter=getClientIP) NSString* ClientIP;

@property (retain,nonatomic,getter=getCommand) NSString* Command;

@property (retain,nonatomic,getter=getCreditCardData) USAePayCreditCardData* CreditCardData;

@property (retain,nonatomic,getter=getCustomerID) NSString* CustomerID;

@property (retain,nonatomic,getter=getCustomFields) USAePayFieldValueArray* CustomFields;

@property (retain,nonatomic,getter=getCustReceipt) NSNumber* CustReceipt;

@property (retain,nonatomic,getter=getCustReceiptName) NSString* CustReceiptName;

@property (retain,nonatomic,getter=getDetails) USAePayTransactionDetail* Details;

@property (retain,nonatomic,getter=getIgnoreDuplicate) NSNumber* IgnoreDuplicate;

@property (retain,nonatomic,getter=getLineItems) USAePayLineItemArray* LineItems;

@property (retain,nonatomic,getter=getRecurringBilling) USAePayRecurringBilling* RecurringBilling;

@property (retain,nonatomic,getter=getRefNum) NSString* RefNum;

@property (retain,nonatomic,getter=getShippingAddress) USAePayAddress* ShippingAddress;

@property (retain,nonatomic,getter=getSoftware) NSString* Software;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayTransactionRequestObject*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end