//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class USAePayProductArray;
@class USAePayHelper;
#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayProductSearchResult : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getProducts) USAePayProductArray* Products;

@property (retain,nonatomic,getter=getProductsMatched) NSNumber* ProductsMatched;

@property (retain,nonatomic,getter=getProductsReturned) NSNumber* ProductsReturned;

@property (retain,nonatomic,getter=getLimit) NSNumber* Limit;

@property (retain,nonatomic,getter=getStartIndex) NSNumber* StartIndex;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayProductSearchResult*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end