//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePaySyncLog.h"


@implementation USAePaySyncLog
@synthesize SyncPosition;
@synthesize ObjectName;
@synthesize RefNum;
@synthesize ChangeDate;
@synthesize Action;
@synthesize any;

+ (USAePaySyncLog *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.SyncPosition =[NSNumber numberWithInt:0];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"SyncPosition"])
                 {
                     if([USAePayHelper isValue:__node name:@"SyncPosition"])
                     {
                         self.SyncPosition = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ObjectName"])
                 {
                     if([USAePayHelper isValue:__node name:@"ObjectName"])
                     {
                         self.ObjectName = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"RefNum"])
                 {
                     if([USAePayHelper isValue:__node name:@"RefNum"])
                     {
                         self.RefNum = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ChangeDate"])
                 {
                     if([USAePayHelper isValue:__node name:@"ChangeDate"])
                     {
                         self.ChangeDate = [USAePayHelper getDate:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Action"])
                 {
                     if([USAePayHelper isValue:__node name:@"Action"])
                     {
                         self.Action = [__node stringValue];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __SyncPositionItemElement=[__request writeElement:SyncPosition type:[NSNumber class] name:@"SyncPosition" URI:@"" parent:__parent skipNullProperty:NO];
    if(__SyncPositionItemElement!=nil)
    {
        [__SyncPositionItemElement setStringValue:[self.SyncPosition stringValue]];
    }
            
    DDXMLElement* __ObjectNameItemElement=[__request writeElement:ObjectName type:[NSString class] name:@"ObjectName" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ObjectNameItemElement!=nil)
    {
        [__ObjectNameItemElement setStringValue:self.ObjectName];
    }
            
    DDXMLElement* __RefNumItemElement=[__request writeElement:RefNum type:[NSString class] name:@"RefNum" URI:@"" parent:__parent skipNullProperty:NO];
    if(__RefNumItemElement!=nil)
    {
        [__RefNumItemElement setStringValue:self.RefNum];
    }
            
    DDXMLElement* __ChangeDateItemElement=[__request writeElement:ChangeDate type:[NSDate class] name:@"ChangeDate" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ChangeDateItemElement!=nil)
    {
        [__ChangeDateItemElement setStringValue:[USAePayHelper getStringFromDateTime:self.ChangeDate]];
    }
            
    DDXMLElement* __ActionItemElement=[__request writeElement:Action type:[NSString class] name:@"Action" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ActionItemElement!=nil)
    {
        [__ActionItemElement setStringValue:self.Action];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
