//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class USAePayHelper;
#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayBatchUploadStatus : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getApproved) NSNumber* Approved;

@property (retain,nonatomic,getter=getUploadRefNum) NSNumber* UploadRefNum;

@property (retain,nonatomic,getter=getDeclined) NSNumber* Declined;

@property (retain,nonatomic,getter=getErrors) NSNumber* Errors;

@property (retain,nonatomic,getter=getFinished) NSString* Finished;

@property (retain,nonatomic,getter=getRemaining) NSNumber* Remaining;

@property (retain,nonatomic,getter=getStarted) NSString* Started;

@property (retain,nonatomic,getter=getStatus) NSString* Status;

@property (retain,nonatomic,getter=getTransactions) NSNumber* Transactions;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayBatchUploadStatus*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end