//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePaySystemInfo : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getApiVersion) NSString* ApiVersion;

@property (retain,nonatomic,getter=getEnvironment) NSString* Environment;

@property (retain,nonatomic,getter=getDatacenter) NSString* Datacenter;

@property (retain,nonatomic,getter=getTime) NSString* Time;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePaySystemInfo*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end