//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePayCurrencyObject.h"


@implementation USAePayCurrencyObject
@synthesize Currency;
@synthesize DecimalPlaces;
@synthesize NumericCode;
@synthesize Rate;
@synthesize TextCode;
@synthesize any;

+ (USAePayCurrencyObject *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.DecimalPlaces =[NSNumber numberWithInt:0];
        self.NumericCode =[NSNumber numberWithInt:0];
        self.Rate =[NSNumber numberWithInt:0];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"Currency"])
                 {
                     if([USAePayHelper isValue:__node name:@"Currency"])
                     {
                         self.Currency = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"DecimalPlaces"])
                 {
                     if([USAePayHelper isValue:__node name:@"DecimalPlaces"])
                     {
                         self.DecimalPlaces = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"NumericCode"])
                 {
                     if([USAePayHelper isValue:__node name:@"NumericCode"])
                     {
                         self.NumericCode = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Rate"])
                 {
                     if([USAePayHelper isValue:__node name:@"Rate"])
                     {
                         self.Rate = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"TextCode"])
                 {
                     if([USAePayHelper isValue:__node name:@"TextCode"])
                     {
                         self.TextCode = [__node stringValue];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __CurrencyItemElement=[__request writeElement:Currency type:[NSString class] name:@"Currency" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CurrencyItemElement!=nil)
    {
        [__CurrencyItemElement setStringValue:self.Currency];
    }
            
    DDXMLElement* __DecimalPlacesItemElement=[__request writeElement:DecimalPlaces type:[NSNumber class] name:@"DecimalPlaces" URI:@"" parent:__parent skipNullProperty:NO];
    if(__DecimalPlacesItemElement!=nil)
    {
        [__DecimalPlacesItemElement setStringValue:[self.DecimalPlaces stringValue]];
    }
            
    DDXMLElement* __NumericCodeItemElement=[__request writeElement:NumericCode type:[NSNumber class] name:@"NumericCode" URI:@"" parent:__parent skipNullProperty:NO];
    if(__NumericCodeItemElement!=nil)
    {
        [__NumericCodeItemElement setStringValue:[self.NumericCode stringValue]];
    }
            
    DDXMLElement* __RateItemElement=[__request writeElement:Rate type:[NSNumber class] name:@"Rate" URI:@"" parent:__parent skipNullProperty:NO];
    if(__RateItemElement!=nil)
    {
        [__RateItemElement setStringValue:[self.Rate stringValue]];
    }
            
    DDXMLElement* __TextCodeItemElement=[__request writeElement:TextCode type:[NSString class] name:@"TextCode" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TextCodeItemElement!=nil)
    {
        [__TextCodeItemElement setStringValue:self.TextCode];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
