//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class USAePayBatchStatusArray;
@class USAePayHelper;
#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayBatchSearchResult : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getBatches) USAePayBatchStatusArray* Batches;

@property (retain,nonatomic,getter=getBatchesMatched) NSNumber* BatchesMatched;

@property (retain,nonatomic,getter=getBatchesReturned) NSNumber* BatchesReturned;

@property (retain,nonatomic,getter=getLimit) NSNumber* Limit;

@property (retain,nonatomic,getter=getStartIndex) NSNumber* StartIndex;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayBatchSearchResult*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end