//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePayAddress.h"


@implementation USAePayAddress
@synthesize City;
@synthesize Company;
@synthesize Country;
@synthesize Email;
@synthesize Fax;
@synthesize FirstName;
@synthesize LastName;
@synthesize Phone;
@synthesize State;
@synthesize Street;
@synthesize Street2;
@synthesize Zip;
@synthesize any;

+ (USAePayAddress *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"City"])
                 {
                     if([USAePayHelper isValue:__node name:@"City"])
                     {
                         self.City = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Company"])
                 {
                     if([USAePayHelper isValue:__node name:@"Company"])
                     {
                         self.Company = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Country"])
                 {
                     if([USAePayHelper isValue:__node name:@"Country"])
                     {
                         self.Country = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Email"])
                 {
                     if([USAePayHelper isValue:__node name:@"Email"])
                     {
                         self.Email = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Fax"])
                 {
                     if([USAePayHelper isValue:__node name:@"Fax"])
                     {
                         self.Fax = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"FirstName"])
                 {
                     if([USAePayHelper isValue:__node name:@"FirstName"])
                     {
                         self.FirstName = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"LastName"])
                 {
                     if([USAePayHelper isValue:__node name:@"LastName"])
                     {
                         self.LastName = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Phone"])
                 {
                     if([USAePayHelper isValue:__node name:@"Phone"])
                     {
                         self.Phone = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"State"])
                 {
                     if([USAePayHelper isValue:__node name:@"State"])
                     {
                         self.State = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Street"])
                 {
                     if([USAePayHelper isValue:__node name:@"Street"])
                     {
                         self.Street = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Street2"])
                 {
                     if([USAePayHelper isValue:__node name:@"Street2"])
                     {
                         self.Street2 = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Zip"])
                 {
                     if([USAePayHelper isValue:__node name:@"Zip"])
                     {
                         self.Zip = [__node stringValue];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __CityItemElement=[__request writeElement:City type:[NSString class] name:@"City" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CityItemElement!=nil)
    {
        [__CityItemElement setStringValue:self.City];
    }
            
    DDXMLElement* __CompanyItemElement=[__request writeElement:Company type:[NSString class] name:@"Company" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CompanyItemElement!=nil)
    {
        [__CompanyItemElement setStringValue:self.Company];
    }
            
    DDXMLElement* __CountryItemElement=[__request writeElement:Country type:[NSString class] name:@"Country" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CountryItemElement!=nil)
    {
        [__CountryItemElement setStringValue:self.Country];
    }
            
    DDXMLElement* __EmailItemElement=[__request writeElement:Email type:[NSString class] name:@"Email" URI:@"" parent:__parent skipNullProperty:YES];
    if(__EmailItemElement!=nil)
    {
        [__EmailItemElement setStringValue:self.Email];
    }
            
    DDXMLElement* __FaxItemElement=[__request writeElement:Fax type:[NSString class] name:@"Fax" URI:@"" parent:__parent skipNullProperty:YES];
    if(__FaxItemElement!=nil)
    {
        [__FaxItemElement setStringValue:self.Fax];
    }
            
    DDXMLElement* __FirstNameItemElement=[__request writeElement:FirstName type:[NSString class] name:@"FirstName" URI:@"" parent:__parent skipNullProperty:YES];
    if(__FirstNameItemElement!=nil)
    {
        [__FirstNameItemElement setStringValue:self.FirstName];
    }
            
    DDXMLElement* __LastNameItemElement=[__request writeElement:LastName type:[NSString class] name:@"LastName" URI:@"" parent:__parent skipNullProperty:YES];
    if(__LastNameItemElement!=nil)
    {
        [__LastNameItemElement setStringValue:self.LastName];
    }
            
    DDXMLElement* __PhoneItemElement=[__request writeElement:Phone type:[NSString class] name:@"Phone" URI:@"" parent:__parent skipNullProperty:YES];
    if(__PhoneItemElement!=nil)
    {
        [__PhoneItemElement setStringValue:self.Phone];
    }
            
    DDXMLElement* __StateItemElement=[__request writeElement:State type:[NSString class] name:@"State" URI:@"" parent:__parent skipNullProperty:YES];
    if(__StateItemElement!=nil)
    {
        [__StateItemElement setStringValue:self.State];
    }
            
    DDXMLElement* __StreetItemElement=[__request writeElement:Street type:[NSString class] name:@"Street" URI:@"" parent:__parent skipNullProperty:YES];
    if(__StreetItemElement!=nil)
    {
        [__StreetItemElement setStringValue:self.Street];
    }
            
    DDXMLElement* __Street2ItemElement=[__request writeElement:Street2 type:[NSString class] name:@"Street2" URI:@"" parent:__parent skipNullProperty:YES];
    if(__Street2ItemElement!=nil)
    {
        [__Street2ItemElement setStringValue:self.Street2];
    }
            
    DDXMLElement* __ZipItemElement=[__request writeElement:Zip type:[NSString class] name:@"Zip" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ZipItemElement!=nil)
    {
        [__ZipItemElement setStringValue:self.Zip];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
