//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePayProductCategory.h"


@implementation USAePayProductCategory
@synthesize ProductCategoryRefNum;
@synthesize Name;
@synthesize Created;
@synthesize Modified;
@synthesize any;

+ (USAePayProductCategory *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"ProductCategoryRefNum"])
                 {
                     if([USAePayHelper isValue:__node name:@"ProductCategoryRefNum"])
                     {
                         self.ProductCategoryRefNum = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Name"])
                 {
                     if([USAePayHelper isValue:__node name:@"Name"])
                     {
                         self.Name = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Created"])
                 {
                     if([USAePayHelper isValue:__node name:@"Created"])
                     {
                         self.Created = [USAePayHelper getDate:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Modified"])
                 {
                     if([USAePayHelper isValue:__node name:@"Modified"])
                     {
                         self.Modified = [USAePayHelper getDate:[__node stringValue]];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __ProductCategoryRefNumItemElement=[__request writeElement:ProductCategoryRefNum type:[NSString class] name:@"ProductCategoryRefNum" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ProductCategoryRefNumItemElement!=nil)
    {
        [__ProductCategoryRefNumItemElement setStringValue:self.ProductCategoryRefNum];
    }
            
    DDXMLElement* __NameItemElement=[__request writeElement:Name type:[NSString class] name:@"Name" URI:@"" parent:__parent skipNullProperty:NO];
    if(__NameItemElement!=nil)
    {
        [__NameItemElement setStringValue:self.Name];
    }
            
    DDXMLElement* __CreatedItemElement=[__request writeElement:Created type:[NSDate class] name:@"Created" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CreatedItemElement!=nil)
    {
        [__CreatedItemElement setStringValue:[USAePayHelper getStringFromDateTime:self.Created]];
    }
            
    DDXMLElement* __ModifiedItemElement=[__request writeElement:Modified type:[NSDate class] name:@"Modified" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ModifiedItemElement!=nil)
    {
        [__ModifiedItemElement setStringValue:[USAePayHelper getStringFromDateTime:self.Modified]];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
