//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayCustomerObjectArray.h"
#import "USAePayHelper.h"
#import "USAePayCustomerSearchResult.h"


@implementation USAePayCustomerSearchResult
@synthesize Customers;
@synthesize CustomersMatched;
@synthesize CustomersReturned;
@synthesize Limit;
@synthesize StartIndex;
@synthesize any;

+ (USAePayCustomerSearchResult *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.Customers =[[USAePayCustomerObjectArray alloc]init];
        self.CustomersMatched =[NSNumber numberWithInt:0];
        self.CustomersReturned =[NSNumber numberWithInt:0];
        self.Limit =[NSNumber numberWithInt:0];
        self.StartIndex =[NSNumber numberWithInt:0];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"Customers"])
                 {
                     if([USAePayHelper isValue:__node name:@"Customers"])
                     {
                         self.Customers = (USAePayCustomerObjectArray*)[__request createObject:__node type:[USAePayCustomerObjectArray class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustomersMatched"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustomersMatched"])
                     {
                         self.CustomersMatched = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustomersReturned"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustomersReturned"])
                     {
                         self.CustomersReturned = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Limit"])
                 {
                     if([USAePayHelper isValue:__node name:@"Limit"])
                     {
                         self.Limit = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"StartIndex"])
                 {
                     if([USAePayHelper isValue:__node name:@"StartIndex"])
                     {
                         self.StartIndex = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __CustomersItemElement=[__request writeElement:Customers type:[USAePayCustomerObjectArray class] name:@"Customers" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CustomersItemElement!=nil)
    {
        [self.Customers serialize:__CustomersItemElement __request: __request];
    }
            
    DDXMLElement* __CustomersMatchedItemElement=[__request writeElement:CustomersMatched type:[NSNumber class] name:@"CustomersMatched" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CustomersMatchedItemElement!=nil)
    {
        [__CustomersMatchedItemElement setStringValue:[self.CustomersMatched stringValue]];
    }
            
    DDXMLElement* __CustomersReturnedItemElement=[__request writeElement:CustomersReturned type:[NSNumber class] name:@"CustomersReturned" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CustomersReturnedItemElement!=nil)
    {
        [__CustomersReturnedItemElement setStringValue:[self.CustomersReturned stringValue]];
    }
            
    DDXMLElement* __LimitItemElement=[__request writeElement:Limit type:[NSNumber class] name:@"Limit" URI:@"" parent:__parent skipNullProperty:NO];
    if(__LimitItemElement!=nil)
    {
        [__LimitItemElement setStringValue:[self.Limit stringValue]];
    }
            
    DDXMLElement* __StartIndexItemElement=[__request writeElement:StartIndex type:[NSNumber class] name:@"StartIndex" URI:@"" parent:__parent skipNullProperty:NO];
    if(__StartIndexItemElement!=nil)
    {
        [__StartIndexItemElement setStringValue:[self.StartIndex stringValue]];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
