//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class USAePayHelper;
#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayCheckData : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getAccount) NSString* Account;

@property (retain,nonatomic,getter=getAccountType) NSString* AccountType;

@property (retain,nonatomic,getter=getCheckNumber) NSNumber* CheckNumber;

@property (retain,nonatomic,getter=getDriversLicense) NSString* DriversLicense;

@property (retain,nonatomic,getter=getDriversLicenseState) NSString* DriversLicenseState;

@property (retain,nonatomic,getter=getRecordType) NSString* RecordType;

@property (retain,nonatomic,getter=getRouting) NSString* Routing;

@property (retain,nonatomic,getter=getAuxOnUS) NSString* AuxOnUS;

@property (retain,nonatomic,getter=getEpcCode) NSString* EpcCode;

@property (retain,nonatomic,getter=getFrontImage) NSString* FrontImage;

@property (retain,nonatomic,getter=getBackImage) NSString* BackImage;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayCheckData*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end