//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayueHash.h"
#import "USAePayHelper.h"
#import "USAePayueSecurityToken.h"


@implementation USAePayueSecurityToken
@synthesize ClientIP;
@synthesize PinHash;
@synthesize SourceKey;
@synthesize any;

+ (USAePayueSecurityToken *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"ClientIP"])
                 {
                     if([USAePayHelper isValue:__node name:@"ClientIP"])
                     {
                         self.ClientIP = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"PinHash"])
                 {
                     if([USAePayHelper isValue:__node name:@"PinHash"])
                     {
                         self.PinHash = (USAePayueHash*)[__request createObject:__node type:[USAePayueHash class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"SourceKey"])
                 {
                     if([USAePayHelper isValue:__node name:@"SourceKey"])
                     {
                         self.SourceKey = [__node stringValue];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __ClientIPItemElement=[__request writeElement:ClientIP type:[NSString class] name:@"ClientIP" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ClientIPItemElement!=nil)
    {
        [__ClientIPItemElement setStringValue:self.ClientIP];
    }
            
    DDXMLElement* __PinHashItemElement=[__request writeElement:PinHash type:[USAePayueHash class] name:@"PinHash" URI:@"" parent:__parent skipNullProperty:NO];
    if(__PinHashItemElement!=nil)
    {
        [self.PinHash serialize:__PinHashItemElement __request: __request];
    }
            
    DDXMLElement* __SourceKeyItemElement=[__request writeElement:SourceKey type:[NSString class] name:@"SourceKey" URI:@"" parent:__parent skipNullProperty:NO];
    if(__SourceKeyItemElement!=nil)
    {
        [__SourceKeyItemElement setStringValue:self.SourceKey];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
