//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class USAePayHelper;
#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayCurrencyObject : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getCurrency) NSString* Currency;

@property (retain,nonatomic,getter=getDecimalPlaces) NSNumber* DecimalPlaces;

@property (retain,nonatomic,getter=getNumericCode) NSNumber* NumericCode;

@property (retain,nonatomic,getter=getRate) NSNumber* Rate;

@property (retain,nonatomic,getter=getTextCode) NSString* TextCode;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayCurrencyObject*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end