//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayAddress.h"
#import "USAePayCheckData.h"
#import "USAePayCreditCardData.h"
#import "USAePayFieldValueArray.h"
#import "USAePayTransactionDetail.h"
#import "USAePayLineItemArray.h"
#import "USAePayRecurringBilling.h"
#import "USAePayHelper.h"
#import "USAePayTransactionRequestObject.h"


@implementation USAePayTransactionRequestObject
@synthesize AccountHolder;
@synthesize AuthCode;
@synthesize BillingAddress;
@synthesize CheckData;
@synthesize ClientIP;
@synthesize Command;
@synthesize CreditCardData;
@synthesize CustomerID;
@synthesize CustomFields;
@synthesize CustReceipt;
@synthesize CustReceiptName;
@synthesize Details;
@synthesize IgnoreDuplicate;
@synthesize LineItems;
@synthesize RecurringBilling;
@synthesize RefNum;
@synthesize ShippingAddress;
@synthesize Software;
@synthesize any;

+ (USAePayTransactionRequestObject *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.CustomFields =[[USAePayFieldValueArray alloc]init];
        self.LineItems =[[USAePayLineItemArray alloc]init];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"AccountHolder"])
                 {
                     if([USAePayHelper isValue:__node name:@"AccountHolder"])
                     {
                         self.AccountHolder = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"AuthCode"])
                 {
                     if([USAePayHelper isValue:__node name:@"AuthCode"])
                     {
                         self.AuthCode = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"BillingAddress"])
                 {
                     if([USAePayHelper isValue:__node name:@"BillingAddress"])
                     {
                         self.BillingAddress = (USAePayAddress*)[__request createObject:__node type:[USAePayAddress class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CheckData"])
                 {
                     if([USAePayHelper isValue:__node name:@"CheckData"])
                     {
                         self.CheckData = (USAePayCheckData*)[__request createObject:__node type:[USAePayCheckData class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ClientIP"])
                 {
                     if([USAePayHelper isValue:__node name:@"ClientIP"])
                     {
                         self.ClientIP = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Command"])
                 {
                     if([USAePayHelper isValue:__node name:@"Command"])
                     {
                         self.Command = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CreditCardData"])
                 {
                     if([USAePayHelper isValue:__node name:@"CreditCardData"])
                     {
                         self.CreditCardData = (USAePayCreditCardData*)[__request createObject:__node type:[USAePayCreditCardData class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustomerID"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustomerID"])
                     {
                         self.CustomerID = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustomFields"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustomFields"])
                     {
                         self.CustomFields = (USAePayFieldValueArray*)[__request createObject:__node type:[USAePayFieldValueArray class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustReceipt"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustReceipt"])
                     {
                         self.CustReceipt = [[NSNumber alloc]initWithBool:[[__node stringValue] boolValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustReceiptName"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustReceiptName"])
                     {
                         self.CustReceiptName = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Details"])
                 {
                     if([USAePayHelper isValue:__node name:@"Details"])
                     {
                         self.Details = (USAePayTransactionDetail*)[__request createObject:__node type:[USAePayTransactionDetail class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"IgnoreDuplicate"])
                 {
                     if([USAePayHelper isValue:__node name:@"IgnoreDuplicate"])
                     {
                         self.IgnoreDuplicate = [[NSNumber alloc]initWithBool:[[__node stringValue] boolValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"LineItems"])
                 {
                     if([USAePayHelper isValue:__node name:@"LineItems"])
                     {
                         self.LineItems = (USAePayLineItemArray*)[__request createObject:__node type:[USAePayLineItemArray class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"RecurringBilling"])
                 {
                     if([USAePayHelper isValue:__node name:@"RecurringBilling"])
                     {
                         self.RecurringBilling = (USAePayRecurringBilling*)[__request createObject:__node type:[USAePayRecurringBilling class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"RefNum"])
                 {
                     if([USAePayHelper isValue:__node name:@"RefNum"])
                     {
                         self.RefNum = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ShippingAddress"])
                 {
                     if([USAePayHelper isValue:__node name:@"ShippingAddress"])
                     {
                         self.ShippingAddress = (USAePayAddress*)[__request createObject:__node type:[USAePayAddress class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Software"])
                 {
                     if([USAePayHelper isValue:__node name:@"Software"])
                     {
                         self.Software = [__node stringValue];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __AccountHolderItemElement=[__request writeElement:AccountHolder type:[NSString class] name:@"AccountHolder" URI:@"" parent:__parent skipNullProperty:YES];
    if(__AccountHolderItemElement!=nil)
    {
        [__AccountHolderItemElement setStringValue:self.AccountHolder];
    }
            
    DDXMLElement* __AuthCodeItemElement=[__request writeElement:AuthCode type:[NSString class] name:@"AuthCode" URI:@"" parent:__parent skipNullProperty:YES];
    if(__AuthCodeItemElement!=nil)
    {
        [__AuthCodeItemElement setStringValue:self.AuthCode];
    }
            
    DDXMLElement* __BillingAddressItemElement=[__request writeElement:BillingAddress type:[USAePayAddress class] name:@"BillingAddress" URI:@"" parent:__parent skipNullProperty:YES];
    if(__BillingAddressItemElement!=nil)
    {
        [self.BillingAddress serialize:__BillingAddressItemElement __request: __request];
    }
            
    DDXMLElement* __CheckDataItemElement=[__request writeElement:CheckData type:[USAePayCheckData class] name:@"CheckData" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CheckDataItemElement!=nil)
    {
        [self.CheckData serialize:__CheckDataItemElement __request: __request];
    }
            
    DDXMLElement* __ClientIPItemElement=[__request writeElement:ClientIP type:[NSString class] name:@"ClientIP" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ClientIPItemElement!=nil)
    {
        [__ClientIPItemElement setStringValue:self.ClientIP];
    }
            
    DDXMLElement* __CommandItemElement=[__request writeElement:Command type:[NSString class] name:@"Command" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CommandItemElement!=nil)
    {
        [__CommandItemElement setStringValue:self.Command];
    }
            
    DDXMLElement* __CreditCardDataItemElement=[__request writeElement:CreditCardData type:[USAePayCreditCardData class] name:@"CreditCardData" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CreditCardDataItemElement!=nil)
    {
        [self.CreditCardData serialize:__CreditCardDataItemElement __request: __request];
    }
            
    DDXMLElement* __CustomerIDItemElement=[__request writeElement:CustomerID type:[NSString class] name:@"CustomerID" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CustomerIDItemElement!=nil)
    {
        [__CustomerIDItemElement setStringValue:self.CustomerID];
    }
            
    DDXMLElement* __CustomFieldsItemElement=[__request writeElement:CustomFields type:[USAePayFieldValueArray class] name:@"CustomFields" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CustomFieldsItemElement!=nil)
    {
        [self.CustomFields serialize:__CustomFieldsItemElement __request: __request];
    }
            
    DDXMLElement* __CustReceiptItemElement=[__request writeElement:CustReceipt type:[NSNumber class] name:@"CustReceipt" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CustReceiptItemElement!=nil)
    {
        [__CustReceiptItemElement setStringValue:[USAePayHelper toBoolStringFromNumber:self.CustReceipt]];
    }
            
    DDXMLElement* __CustReceiptNameItemElement=[__request writeElement:CustReceiptName type:[NSString class] name:@"CustReceiptName" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CustReceiptNameItemElement!=nil)
    {
        [__CustReceiptNameItemElement setStringValue:self.CustReceiptName];
    }
            
    DDXMLElement* __DetailsItemElement=[__request writeElement:Details type:[USAePayTransactionDetail class] name:@"Details" URI:@"" parent:__parent skipNullProperty:NO];
    if(__DetailsItemElement!=nil)
    {
        [self.Details serialize:__DetailsItemElement __request: __request];
    }
            
    DDXMLElement* __IgnoreDuplicateItemElement=[__request writeElement:IgnoreDuplicate type:[NSNumber class] name:@"IgnoreDuplicate" URI:@"" parent:__parent skipNullProperty:YES];
    if(__IgnoreDuplicateItemElement!=nil)
    {
        [__IgnoreDuplicateItemElement setStringValue:[USAePayHelper toBoolStringFromNumber:self.IgnoreDuplicate]];
    }
            
    DDXMLElement* __LineItemsItemElement=[__request writeElement:LineItems type:[USAePayLineItemArray class] name:@"LineItems" URI:@"" parent:__parent skipNullProperty:YES];
    if(__LineItemsItemElement!=nil)
    {
        [self.LineItems serialize:__LineItemsItemElement __request: __request];
    }
            
    DDXMLElement* __RecurringBillingItemElement=[__request writeElement:RecurringBilling type:[USAePayRecurringBilling class] name:@"RecurringBilling" URI:@"" parent:__parent skipNullProperty:YES];
    if(__RecurringBillingItemElement!=nil)
    {
        [self.RecurringBilling serialize:__RecurringBillingItemElement __request: __request];
    }
            
    DDXMLElement* __RefNumItemElement=[__request writeElement:RefNum type:[NSString class] name:@"RefNum" URI:@"" parent:__parent skipNullProperty:YES];
    if(__RefNumItemElement!=nil)
    {
        [__RefNumItemElement setStringValue:self.RefNum];
    }
            
    DDXMLElement* __ShippingAddressItemElement=[__request writeElement:ShippingAddress type:[USAePayAddress class] name:@"ShippingAddress" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ShippingAddressItemElement!=nil)
    {
        [self.ShippingAddress serialize:__ShippingAddressItemElement __request: __request];
    }
            
    DDXMLElement* __SoftwareItemElement=[__request writeElement:Software type:[NSString class] name:@"Software" URI:@"" parent:__parent skipNullProperty:YES];
    if(__SoftwareItemElement!=nil)
    {
        [__SoftwareItemElement setStringValue:self.Software];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
