//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayAddress.h"
#import "USAePayCheckData.h"
#import "USAePayCheckTrace.h"
#import "USAePayCreditCardData.h"
#import "USAePayFieldValueArray.h"
#import "USAePayTransactionDetail.h"
#import "USAePayLineItemArray.h"
#import "USAePayTransactionResponse.h"
#import "USAePayHelper.h"
#import "USAePayTransactionObject.h"


@implementation USAePayTransactionObject
@synthesize AccountHolder;
@synthesize BillingAddress;
@synthesize CheckData;
@synthesize CheckTrace;
@synthesize ClientIP;
@synthesize CreditCardData;
@synthesize CustomerID;
@synthesize CustomFields;
@synthesize DateTime;
@synthesize Details;
@synthesize LineItems;
@synthesize Response;
@synthesize ServerIP;
@synthesize ShippingAddress;
@synthesize Source;
@synthesize Status;
@synthesize TransactionType;
@synthesize User;
@synthesize any;

+ (USAePayTransactionObject *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.CustomFields =[[USAePayFieldValueArray alloc]init];
        self.LineItems =[[USAePayLineItemArray alloc]init];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"AccountHolder"])
                 {
                     if([USAePayHelper isValue:__node name:@"AccountHolder"])
                     {
                         self.AccountHolder = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"BillingAddress"])
                 {
                     if([USAePayHelper isValue:__node name:@"BillingAddress"])
                     {
                         self.BillingAddress = (USAePayAddress*)[__request createObject:__node type:[USAePayAddress class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CheckData"])
                 {
                     if([USAePayHelper isValue:__node name:@"CheckData"])
                     {
                         self.CheckData = (USAePayCheckData*)[__request createObject:__node type:[USAePayCheckData class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CheckTrace"])
                 {
                     if([USAePayHelper isValue:__node name:@"CheckTrace"])
                     {
                         self.CheckTrace = (USAePayCheckTrace*)[__request createObject:__node type:[USAePayCheckTrace class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ClientIP"])
                 {
                     if([USAePayHelper isValue:__node name:@"ClientIP"])
                     {
                         self.ClientIP = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CreditCardData"])
                 {
                     if([USAePayHelper isValue:__node name:@"CreditCardData"])
                     {
                         self.CreditCardData = (USAePayCreditCardData*)[__request createObject:__node type:[USAePayCreditCardData class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustomerID"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustomerID"])
                     {
                         self.CustomerID = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustomFields"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustomFields"])
                     {
                         self.CustomFields = (USAePayFieldValueArray*)[__request createObject:__node type:[USAePayFieldValueArray class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"DateTime"])
                 {
                     if([USAePayHelper isValue:__node name:@"DateTime"])
                     {
                         self.DateTime = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Details"])
                 {
                     if([USAePayHelper isValue:__node name:@"Details"])
                     {
                         self.Details = (USAePayTransactionDetail*)[__request createObject:__node type:[USAePayTransactionDetail class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"LineItems"])
                 {
                     if([USAePayHelper isValue:__node name:@"LineItems"])
                     {
                         self.LineItems = (USAePayLineItemArray*)[__request createObject:__node type:[USAePayLineItemArray class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Response"])
                 {
                     if([USAePayHelper isValue:__node name:@"Response"])
                     {
                         self.Response = (USAePayTransactionResponse*)[__request createObject:__node type:[USAePayTransactionResponse class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ServerIP"])
                 {
                     if([USAePayHelper isValue:__node name:@"ServerIP"])
                     {
                         self.ServerIP = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ShippingAddress"])
                 {
                     if([USAePayHelper isValue:__node name:@"ShippingAddress"])
                     {
                         self.ShippingAddress = (USAePayAddress*)[__request createObject:__node type:[USAePayAddress class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Source"])
                 {
                     if([USAePayHelper isValue:__node name:@"Source"])
                     {
                         self.Source = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Status"])
                 {
                     if([USAePayHelper isValue:__node name:@"Status"])
                     {
                         self.Status = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"TransactionType"])
                 {
                     if([USAePayHelper isValue:__node name:@"TransactionType"])
                     {
                         self.TransactionType = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"User"])
                 {
                     if([USAePayHelper isValue:__node name:@"User"])
                     {
                         self.User = [__node stringValue];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __AccountHolderItemElement=[__request writeElement:AccountHolder type:[NSString class] name:@"AccountHolder" URI:@"" parent:__parent skipNullProperty:NO];
    if(__AccountHolderItemElement!=nil)
    {
        [__AccountHolderItemElement setStringValue:self.AccountHolder];
    }
            
    DDXMLElement* __BillingAddressItemElement=[__request writeElement:BillingAddress type:[USAePayAddress class] name:@"BillingAddress" URI:@"" parent:__parent skipNullProperty:NO];
    if(__BillingAddressItemElement!=nil)
    {
        [self.BillingAddress serialize:__BillingAddressItemElement __request: __request];
    }
            
    DDXMLElement* __CheckDataItemElement=[__request writeElement:CheckData type:[USAePayCheckData class] name:@"CheckData" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CheckDataItemElement!=nil)
    {
        [self.CheckData serialize:__CheckDataItemElement __request: __request];
    }
            
    DDXMLElement* __CheckTraceItemElement=[__request writeElement:CheckTrace type:[USAePayCheckTrace class] name:@"CheckTrace" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CheckTraceItemElement!=nil)
    {
        [self.CheckTrace serialize:__CheckTraceItemElement __request: __request];
    }
            
    DDXMLElement* __ClientIPItemElement=[__request writeElement:ClientIP type:[NSString class] name:@"ClientIP" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ClientIPItemElement!=nil)
    {
        [__ClientIPItemElement setStringValue:self.ClientIP];
    }
            
    DDXMLElement* __CreditCardDataItemElement=[__request writeElement:CreditCardData type:[USAePayCreditCardData class] name:@"CreditCardData" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CreditCardDataItemElement!=nil)
    {
        [self.CreditCardData serialize:__CreditCardDataItemElement __request: __request];
    }
            
    DDXMLElement* __CustomerIDItemElement=[__request writeElement:CustomerID type:[NSString class] name:@"CustomerID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CustomerIDItemElement!=nil)
    {
        [__CustomerIDItemElement setStringValue:self.CustomerID];
    }
            
    DDXMLElement* __CustomFieldsItemElement=[__request writeElement:CustomFields type:[USAePayFieldValueArray class] name:@"CustomFields" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CustomFieldsItemElement!=nil)
    {
        [self.CustomFields serialize:__CustomFieldsItemElement __request: __request];
    }
            
    DDXMLElement* __DateTimeItemElement=[__request writeElement:DateTime type:[NSString class] name:@"DateTime" URI:@"" parent:__parent skipNullProperty:NO];
    if(__DateTimeItemElement!=nil)
    {
        [__DateTimeItemElement setStringValue:self.DateTime];
    }
            
    DDXMLElement* __DetailsItemElement=[__request writeElement:Details type:[USAePayTransactionDetail class] name:@"Details" URI:@"" parent:__parent skipNullProperty:NO];
    if(__DetailsItemElement!=nil)
    {
        [self.Details serialize:__DetailsItemElement __request: __request];
    }
            
    DDXMLElement* __LineItemsItemElement=[__request writeElement:LineItems type:[USAePayLineItemArray class] name:@"LineItems" URI:@"" parent:__parent skipNullProperty:YES];
    if(__LineItemsItemElement!=nil)
    {
        [self.LineItems serialize:__LineItemsItemElement __request: __request];
    }
            
    DDXMLElement* __ResponseItemElement=[__request writeElement:Response type:[USAePayTransactionResponse class] name:@"Response" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ResponseItemElement!=nil)
    {
        [self.Response serialize:__ResponseItemElement __request: __request];
    }
            
    DDXMLElement* __ServerIPItemElement=[__request writeElement:ServerIP type:[NSString class] name:@"ServerIP" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ServerIPItemElement!=nil)
    {
        [__ServerIPItemElement setStringValue:self.ServerIP];
    }
            
    DDXMLElement* __ShippingAddressItemElement=[__request writeElement:ShippingAddress type:[USAePayAddress class] name:@"ShippingAddress" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ShippingAddressItemElement!=nil)
    {
        [self.ShippingAddress serialize:__ShippingAddressItemElement __request: __request];
    }
            
    DDXMLElement* __SourceItemElement=[__request writeElement:Source type:[NSString class] name:@"Source" URI:@"" parent:__parent skipNullProperty:NO];
    if(__SourceItemElement!=nil)
    {
        [__SourceItemElement setStringValue:self.Source];
    }
            
    DDXMLElement* __StatusItemElement=[__request writeElement:Status type:[NSString class] name:@"Status" URI:@"" parent:__parent skipNullProperty:NO];
    if(__StatusItemElement!=nil)
    {
        [__StatusItemElement setStringValue:self.Status];
    }
            
    DDXMLElement* __TransactionTypeItemElement=[__request writeElement:TransactionType type:[NSString class] name:@"TransactionType" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TransactionTypeItemElement!=nil)
    {
        [__TransactionTypeItemElement setStringValue:self.TransactionType];
    }
            
    DDXMLElement* __UserItemElement=[__request writeElement:User type:[NSString class] name:@"User" URI:@"" parent:__parent skipNullProperty:NO];
    if(__UserItemElement!=nil)
    {
        [__UserItemElement setStringValue:self.User];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
