//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class USAePayHelper;
@class USAePayProductInventoryArray;
@class USAePayPriceTierArray;
#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayProduct : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getProductRefNum) NSString* ProductRefNum;

@property (retain,nonatomic,getter=getProductID) NSString* ProductID;

@property (retain,nonatomic,getter=getSKU) NSString* SKU;

@property (retain,nonatomic,getter=getUPC) NSString* UPC;

@property (retain,nonatomic,getter=getCategory) NSString* Category;

@property (retain,nonatomic,getter=getEnabled) NSNumber* Enabled;

@property (retain,nonatomic,getter=getName) NSString* Name;

@property (retain,nonatomic,getter=getDescription) NSString* Description;

@property (retain,nonatomic,getter=getModel) NSString* Model;

@property (retain,nonatomic,getter=getWeight) NSNumber* Weight;

@property (retain,nonatomic,getter=getShipWeight) NSNumber* ShipWeight;

@property (retain,nonatomic,getter=getPrice) NSNumber* Price;

@property (retain,nonatomic,getter=getWholesalePrice) NSNumber* WholesalePrice;

@property (retain,nonatomic,getter=getListPrice) NSNumber* ListPrice;

@property (retain,nonatomic,getter=getDateAvailable) NSString* DateAvailable;

@property (retain,nonatomic,getter=getManufacturer) NSString* Manufacturer;

@property (retain,nonatomic,getter=getPhysicalGood) NSNumber* PhysicalGood;

@property (retain,nonatomic,getter=getTaxClass) NSString* TaxClass;

@property (retain,nonatomic,getter=getMinQuantity) NSNumber* MinQuantity;

@property (retain,nonatomic,getter=getImageURL) NSString* ImageURL;

@property (retain,nonatomic,getter=getURL) NSString* URL;

@property (retain,nonatomic,getter=getCreated) NSDate* Created;

@property (retain,nonatomic,getter=getModified) NSDate* Modified;

@property (retain,nonatomic,getter=getInventory) USAePayProductInventoryArray* Inventory;

@property (retain,nonatomic,getter=getPriceTiers) USAePayPriceTierArray* PriceTiers;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayProduct*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end