//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayFieldValueArray.h"
#import "USAePayTransactionDetail.h"
#import "USAePayLineItemArray.h"
#import "USAePayHelper.h"
#import "USAePayCustomerTransactionRequest.h"


@implementation USAePayCustomerTransactionRequest
@synthesize Command;
@synthesize CardCode;
@synthesize ClientIP;
@synthesize CustomFields;
@synthesize CustReceipt;
@synthesize CustReceiptEmail;
@synthesize CustReceiptName;
@synthesize MerchReceipt;
@synthesize MerchReceiptEmail;
@synthesize MerchReceiptName;
@synthesize Details;
@synthesize IgnoreDuplicate;
@synthesize isRecurring;
@synthesize LineItems;
@synthesize Software;
@synthesize any;

+ (USAePayCustomerTransactionRequest *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.CustomFields =[[USAePayFieldValueArray alloc]init];
        self.LineItems =[[USAePayLineItemArray alloc]init];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"Command"])
                 {
                     if([USAePayHelper isValue:__node name:@"Command"])
                     {
                         self.Command = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CardCode"])
                 {
                     if([USAePayHelper isValue:__node name:@"CardCode"])
                     {
                         self.CardCode = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ClientIP"])
                 {
                     if([USAePayHelper isValue:__node name:@"ClientIP"])
                     {
                         self.ClientIP = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustomFields"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustomFields"])
                     {
                         self.CustomFields = (USAePayFieldValueArray*)[__request createObject:__node type:[USAePayFieldValueArray class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustReceipt"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustReceipt"])
                     {
                         self.CustReceipt = [[NSNumber alloc]initWithBool:[[__node stringValue] boolValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustReceiptEmail"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustReceiptEmail"])
                     {
                         self.CustReceiptEmail = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustReceiptName"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustReceiptName"])
                     {
                         self.CustReceiptName = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"MerchReceipt"])
                 {
                     if([USAePayHelper isValue:__node name:@"MerchReceipt"])
                     {
                         self.MerchReceipt = [[NSNumber alloc]initWithBool:[[__node stringValue] boolValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"MerchReceiptEmail"])
                 {
                     if([USAePayHelper isValue:__node name:@"MerchReceiptEmail"])
                     {
                         self.MerchReceiptEmail = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"MerchReceiptName"])
                 {
                     if([USAePayHelper isValue:__node name:@"MerchReceiptName"])
                     {
                         self.MerchReceiptName = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Details"])
                 {
                     if([USAePayHelper isValue:__node name:@"Details"])
                     {
                         self.Details = (USAePayTransactionDetail*)[__request createObject:__node type:[USAePayTransactionDetail class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"IgnoreDuplicate"])
                 {
                     if([USAePayHelper isValue:__node name:@"IgnoreDuplicate"])
                     {
                         self.IgnoreDuplicate = [[NSNumber alloc]initWithBool:[[__node stringValue] boolValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"isRecurring"])
                 {
                     if([USAePayHelper isValue:__node name:@"isRecurring"])
                     {
                         self.isRecurring = [[NSNumber alloc]initWithBool:[[__node stringValue] boolValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"LineItems"])
                 {
                     if([USAePayHelper isValue:__node name:@"LineItems"])
                     {
                         self.LineItems = (USAePayLineItemArray*)[__request createObject:__node type:[USAePayLineItemArray class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Software"])
                 {
                     if([USAePayHelper isValue:__node name:@"Software"])
                     {
                         self.Software = [__node stringValue];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __CommandItemElement=[__request writeElement:Command type:[NSString class] name:@"Command" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CommandItemElement!=nil)
    {
        [__CommandItemElement setStringValue:self.Command];
    }
            
    DDXMLElement* __CardCodeItemElement=[__request writeElement:CardCode type:[NSString class] name:@"CardCode" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CardCodeItemElement!=nil)
    {
        [__CardCodeItemElement setStringValue:self.CardCode];
    }
            
    DDXMLElement* __ClientIPItemElement=[__request writeElement:ClientIP type:[NSString class] name:@"ClientIP" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ClientIPItemElement!=nil)
    {
        [__ClientIPItemElement setStringValue:self.ClientIP];
    }
            
    DDXMLElement* __CustomFieldsItemElement=[__request writeElement:CustomFields type:[USAePayFieldValueArray class] name:@"CustomFields" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CustomFieldsItemElement!=nil)
    {
        [self.CustomFields serialize:__CustomFieldsItemElement __request: __request];
    }
            
    DDXMLElement* __CustReceiptItemElement=[__request writeElement:CustReceipt type:[NSNumber class] name:@"CustReceipt" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CustReceiptItemElement!=nil)
    {
        [__CustReceiptItemElement setStringValue:[USAePayHelper toBoolStringFromNumber:self.CustReceipt]];
    }
            
    DDXMLElement* __CustReceiptEmailItemElement=[__request writeElement:CustReceiptEmail type:[NSString class] name:@"CustReceiptEmail" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CustReceiptEmailItemElement!=nil)
    {
        [__CustReceiptEmailItemElement setStringValue:self.CustReceiptEmail];
    }
            
    DDXMLElement* __CustReceiptNameItemElement=[__request writeElement:CustReceiptName type:[NSString class] name:@"CustReceiptName" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CustReceiptNameItemElement!=nil)
    {
        [__CustReceiptNameItemElement setStringValue:self.CustReceiptName];
    }
            
    DDXMLElement* __MerchReceiptItemElement=[__request writeElement:MerchReceipt type:[NSNumber class] name:@"MerchReceipt" URI:@"" parent:__parent skipNullProperty:YES];
    if(__MerchReceiptItemElement!=nil)
    {
        [__MerchReceiptItemElement setStringValue:[USAePayHelper toBoolStringFromNumber:self.MerchReceipt]];
    }
            
    DDXMLElement* __MerchReceiptEmailItemElement=[__request writeElement:MerchReceiptEmail type:[NSString class] name:@"MerchReceiptEmail" URI:@"" parent:__parent skipNullProperty:YES];
    if(__MerchReceiptEmailItemElement!=nil)
    {
        [__MerchReceiptEmailItemElement setStringValue:self.MerchReceiptEmail];
    }
            
    DDXMLElement* __MerchReceiptNameItemElement=[__request writeElement:MerchReceiptName type:[NSString class] name:@"MerchReceiptName" URI:@"" parent:__parent skipNullProperty:YES];
    if(__MerchReceiptNameItemElement!=nil)
    {
        [__MerchReceiptNameItemElement setStringValue:self.MerchReceiptName];
    }
            
    DDXMLElement* __DetailsItemElement=[__request writeElement:Details type:[USAePayTransactionDetail class] name:@"Details" URI:@"" parent:__parent skipNullProperty:NO];
    if(__DetailsItemElement!=nil)
    {
        [self.Details serialize:__DetailsItemElement __request: __request];
    }
            
    DDXMLElement* __IgnoreDuplicateItemElement=[__request writeElement:IgnoreDuplicate type:[NSNumber class] name:@"IgnoreDuplicate" URI:@"" parent:__parent skipNullProperty:YES];
    if(__IgnoreDuplicateItemElement!=nil)
    {
        [__IgnoreDuplicateItemElement setStringValue:[USAePayHelper toBoolStringFromNumber:self.IgnoreDuplicate]];
    }
            
    DDXMLElement* __isRecurringItemElement=[__request writeElement:isRecurring type:[NSNumber class] name:@"isRecurring" URI:@"" parent:__parent skipNullProperty:YES];
    if(__isRecurringItemElement!=nil)
    {
        [__isRecurringItemElement setStringValue:[USAePayHelper toBoolStringFromNumber:self.isRecurring]];
    }
            
    DDXMLElement* __LineItemsItemElement=[__request writeElement:LineItems type:[USAePayLineItemArray class] name:@"LineItems" URI:@"" parent:__parent skipNullProperty:YES];
    if(__LineItemsItemElement!=nil)
    {
        [self.LineItems serialize:__LineItemsItemElement __request: __request];
    }
            
    DDXMLElement* __SoftwareItemElement=[__request writeElement:Software type:[NSString class] name:@"Software" URI:@"" parent:__parent skipNullProperty:YES];
    if(__SoftwareItemElement!=nil)
    {
        [__SoftwareItemElement setStringValue:self.Software];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
