//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePayueHash.h"


@implementation USAePayueHash
@synthesize HashValue;
@synthesize Seed;
@synthesize Type;
@synthesize any;

+ (USAePayueHash *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"HashValue"])
                 {
                     if([USAePayHelper isValue:__node name:@"HashValue"])
                     {
                         self.HashValue = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Seed"])
                 {
                     if([USAePayHelper isValue:__node name:@"Seed"])
                     {
                         self.Seed = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Type"])
                 {
                     if([USAePayHelper isValue:__node name:@"Type"])
                     {
                         self.Type = [__node stringValue];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __HashValueItemElement=[__request writeElement:HashValue type:[NSString class] name:@"HashValue" URI:@"" parent:__parent skipNullProperty:NO];
    if(__HashValueItemElement!=nil)
    {
        [__HashValueItemElement setStringValue:self.HashValue];
    }
            
    DDXMLElement* __SeedItemElement=[__request writeElement:Seed type:[NSString class] name:@"Seed" URI:@"" parent:__parent skipNullProperty:NO];
    if(__SeedItemElement!=nil)
    {
        [__SeedItemElement setStringValue:self.Seed];
    }
            
    DDXMLElement* __TypeItemElement=[__request writeElement:Type type:[NSString class] name:@"Type" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TypeItemElement!=nil)
    {
        [__TypeItemElement setStringValue:self.Type];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
