//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePaySystemInfo.h"


@implementation USAePaySystemInfo
@synthesize ApiVersion;
@synthesize Environment;
@synthesize Datacenter;
@synthesize Time;
@synthesize any;

+ (USAePaySystemInfo *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"ApiVersion"])
                 {
                     if([USAePayHelper isValue:__node name:@"ApiVersion"])
                     {
                         self.ApiVersion = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Environment"])
                 {
                     if([USAePayHelper isValue:__node name:@"Environment"])
                     {
                         self.Environment = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Datacenter"])
                 {
                     if([USAePayHelper isValue:__node name:@"Datacenter"])
                     {
                         self.Datacenter = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Time"])
                 {
                     if([USAePayHelper isValue:__node name:@"Time"])
                     {
                         self.Time = [__node stringValue];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __ApiVersionItemElement=[__request writeElement:ApiVersion type:[NSString class] name:@"ApiVersion" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ApiVersionItemElement!=nil)
    {
        [__ApiVersionItemElement setStringValue:self.ApiVersion];
    }
            
    DDXMLElement* __EnvironmentItemElement=[__request writeElement:Environment type:[NSString class] name:@"Environment" URI:@"" parent:__parent skipNullProperty:NO];
    if(__EnvironmentItemElement!=nil)
    {
        [__EnvironmentItemElement setStringValue:self.Environment];
    }
            
    DDXMLElement* __DatacenterItemElement=[__request writeElement:Datacenter type:[NSString class] name:@"Datacenter" URI:@"" parent:__parent skipNullProperty:NO];
    if(__DatacenterItemElement!=nil)
    {
        [__DatacenterItemElement setStringValue:self.Datacenter];
    }
            
    DDXMLElement* __TimeItemElement=[__request writeElement:Time type:[NSString class] name:@"Time" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TimeItemElement!=nil)
    {
        [__TimeItemElement setStringValue:self.Time];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
