//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayCheckTrace : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getStatus) NSString* Status;

@property (retain,nonatomic,getter=getStatusCode) NSString* StatusCode;

@property (retain,nonatomic,getter=getBankNote) NSString* BankNote;

@property (retain,nonatomic,getter=getEffective) NSString* Effective;

@property (retain,nonatomic,getter=getProcessed) NSString* Processed;

@property (retain,nonatomic,getter=getReturned) NSString* Returned;

@property (retain,nonatomic,getter=getReturnCode) NSString* ReturnCode;

@property (retain,nonatomic,getter=getReason) NSString* Reason;

@property (retain,nonatomic,getter=getSettled) NSString* Settled;

@property (retain,nonatomic,getter=getTrackingNum) NSString* TrackingNum;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayCheckTrace*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end