//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class USAePayHelper;
#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayReceipt : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getReceiptRefNum) NSNumber* ReceiptRefNum;

@property (retain,nonatomic,getter=getName) NSString* Name;

@property (retain,nonatomic,getter=getSubject) NSString* Subject;

@property (retain,nonatomic,getter=getFromEmail) NSString* FromEmail;

@property (retain,nonatomic,getter=getTarget) NSString* Target;

@property (retain,nonatomic,getter=getContentType) NSString* ContentType;

@property (retain,nonatomic,getter=getTemplateHTML) NSString* TemplateHTML;

@property (retain,nonatomic,getter=getTemplateText) NSString* TemplateText;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayReceipt*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end