//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class USAePayCustomerObjectArray;
@class USAePayHelper;
#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayCustomerSearchResult : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getCustomers) USAePayCustomerObjectArray* Customers;

@property (retain,nonatomic,getter=getCustomersMatched) NSNumber* CustomersMatched;

@property (retain,nonatomic,getter=getCustomersReturned) NSNumber* CustomersReturned;

@property (retain,nonatomic,getter=getLimit) NSNumber* Limit;

@property (retain,nonatomic,getter=getStartIndex) NSNumber* StartIndex;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayCustomerSearchResult*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end