//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>
#import "DDXML.h"
#import "MIMEKit.h"
@protocol USAePayIReferenceObject
@end
    
@class USAePayRequestResultHandler;
typedef void (^USAePayCLB)(USAePayRequestResultHandler *);

#define SOAPVERSION_10      1
#define SOAPVERSION_11      2
#define SOAPVERSION_12      3

@interface USAePayRequestResultHandler : NSObject
{
    NSMutableDictionary* referencesTable;
    NSMutableDictionary* reverseReferencesTable;
    NSMutableData* receivedBuffer;
    NSURLConnection* connection;
    NSMutableDictionary* namespaces;
    DDXMLDocument *xml;
    NSURLResponse* responseObj;
    int soapVersion;
    NSString* envNS;
    NSMutableDictionary* attachments;
    PKMIMEMessage *mimeMessage;
}
@property BOOL EnableLogging;
@property (retain, nonatomic) DDXMLElement* Body;
@property (retain, nonatomic) DDXMLElement* Header;    
@property (retain, nonatomic) DDXMLElement* OutputHeader;
@property (retain, nonatomic) DDXMLElement* OutputBody;
@property (retain, nonatomic) NSError* OutputFault;
@property (nonatomic,copy) USAePayCLB Callback;
@property BOOL EnableMTOM;

-(id) init;
-(id)init:(int) version;
-(id)createObject: (DDXMLElement*) node type:(Class) type;
-(NSString*) getEnvelopeString;
-(DDXMLDocument*) createEnvelopeXml;
-(id) createInstance:(Class) type node: (DDXMLNode*)node request :(USAePayRequestResultHandler *)request;
-(DDXMLElement*) writeElement:(NSString*)name URI: (NSString*) URI parent:(DDXMLElement*) parent;
-(DDXMLElement*) writeElement:(id)obj type:(Class)type name: (NSString*)name URI: (NSString*) URI parent:(DDXMLElement*) parent skipNullProperty:(BOOL)skipNullProperty;
-(DDXMLNode*) addAttribute:(NSString*) name URI:(NSString*) URI stringValue:(NSString*) stringValue element:(DDXMLElement*) element;
-(void)setResponse:(NSData *)responseData response:(NSURLResponse*) response;
-(void) sendImplementation:(NSMutableURLRequest*) request callbackDelegate:(USAePayCLB) callbackDelegate;
-(void)Cancel;    

-(void) sendImplementation:(NSMutableURLRequest*) request;

-(void)parseMultipartData:(NSData*) responseData contentType:(PKContentType*)contentType;
-(PKMIMEMessage*) getEnvelopeData;
-(PKMIMEData*) attachmentById:(NSString*) contentId;
-(void) prepareRequest:(NSMutableURLRequest*)request;
-(NSData*) getBinary: (DDXMLNode*)element  isSwaRef:(BOOL)isSwaRef isAttribute:(BOOL) isAttribute;
-(void) setBinary:(DDXMLNode*)propertyElement data:(NSData*)data isSwaRef:(BOOL)isSwaRef isAttribute:(BOOL) isAttribute;
-(void) addWS_addressingHeaders:(NSString*) action replyTo:(NSString*) replyTo to:(NSString*) to referenceParameters:(NSMutableArray *)referenceParameters;
-(NSObject*) getAnyTypeValue:(DDXMLElement*) node;
-(void) setAnyTypeValue: (NSObject*)item propertyElement:(DDXMLElement*) propertyElement;
@end

@protocol USAePayISerializableObject
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end