//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePayCheckTrace.h"


@implementation USAePayCheckTrace
@synthesize Status;
@synthesize StatusCode;
@synthesize BankNote;
@synthesize Effective;
@synthesize Processed;
@synthesize Returned;
@synthesize ReturnCode;
@synthesize Reason;
@synthesize Settled;
@synthesize TrackingNum;
@synthesize any;

+ (USAePayCheckTrace *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"Status"])
                 {
                     if([USAePayHelper isValue:__node name:@"Status"])
                     {
                         self.Status = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"StatusCode"])
                 {
                     if([USAePayHelper isValue:__node name:@"StatusCode"])
                     {
                         self.StatusCode = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"BankNote"])
                 {
                     if([USAePayHelper isValue:__node name:@"BankNote"])
                     {
                         self.BankNote = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Effective"])
                 {
                     if([USAePayHelper isValue:__node name:@"Effective"])
                     {
                         self.Effective = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Processed"])
                 {
                     if([USAePayHelper isValue:__node name:@"Processed"])
                     {
                         self.Processed = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Returned"])
                 {
                     if([USAePayHelper isValue:__node name:@"Returned"])
                     {
                         self.Returned = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ReturnCode"])
                 {
                     if([USAePayHelper isValue:__node name:@"ReturnCode"])
                     {
                         self.ReturnCode = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Reason"])
                 {
                     if([USAePayHelper isValue:__node name:@"Reason"])
                     {
                         self.Reason = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Settled"])
                 {
                     if([USAePayHelper isValue:__node name:@"Settled"])
                     {
                         self.Settled = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"TrackingNum"])
                 {
                     if([USAePayHelper isValue:__node name:@"TrackingNum"])
                     {
                         self.TrackingNum = [__node stringValue];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __StatusItemElement=[__request writeElement:Status type:[NSString class] name:@"Status" URI:@"" parent:__parent skipNullProperty:YES];
    if(__StatusItemElement!=nil)
    {
        [__StatusItemElement setStringValue:self.Status];
    }
            
    DDXMLElement* __StatusCodeItemElement=[__request writeElement:StatusCode type:[NSString class] name:@"StatusCode" URI:@"" parent:__parent skipNullProperty:YES];
    if(__StatusCodeItemElement!=nil)
    {
        [__StatusCodeItemElement setStringValue:self.StatusCode];
    }
            
    DDXMLElement* __BankNoteItemElement=[__request writeElement:BankNote type:[NSString class] name:@"BankNote" URI:@"" parent:__parent skipNullProperty:YES];
    if(__BankNoteItemElement!=nil)
    {
        [__BankNoteItemElement setStringValue:self.BankNote];
    }
            
    DDXMLElement* __EffectiveItemElement=[__request writeElement:Effective type:[NSString class] name:@"Effective" URI:@"" parent:__parent skipNullProperty:YES];
    if(__EffectiveItemElement!=nil)
    {
        [__EffectiveItemElement setStringValue:self.Effective];
    }
            
    DDXMLElement* __ProcessedItemElement=[__request writeElement:Processed type:[NSString class] name:@"Processed" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ProcessedItemElement!=nil)
    {
        [__ProcessedItemElement setStringValue:self.Processed];
    }
            
    DDXMLElement* __ReturnedItemElement=[__request writeElement:Returned type:[NSString class] name:@"Returned" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ReturnedItemElement!=nil)
    {
        [__ReturnedItemElement setStringValue:self.Returned];
    }
            
    DDXMLElement* __ReturnCodeItemElement=[__request writeElement:ReturnCode type:[NSString class] name:@"ReturnCode" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ReturnCodeItemElement!=nil)
    {
        [__ReturnCodeItemElement setStringValue:self.ReturnCode];
    }
            
    DDXMLElement* __ReasonItemElement=[__request writeElement:Reason type:[NSString class] name:@"Reason" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ReasonItemElement!=nil)
    {
        [__ReasonItemElement setStringValue:self.Reason];
    }
            
    DDXMLElement* __SettledItemElement=[__request writeElement:Settled type:[NSString class] name:@"Settled" URI:@"" parent:__parent skipNullProperty:YES];
    if(__SettledItemElement!=nil)
    {
        [__SettledItemElement setStringValue:self.Settled];
    }
            
    DDXMLElement* __TrackingNumItemElement=[__request writeElement:TrackingNum type:[NSString class] name:@"TrackingNum" URI:@"" parent:__parent skipNullProperty:YES];
    if(__TrackingNumItemElement!=nil)
    {
        [__TrackingNumItemElement setStringValue:self.TrackingNum];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
