//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePayAddress.h"
#import "USAePayFieldValueArray.h"
#import "USAePayPaymentMethodArray.h"
#import "USAePayCustomerObject.h"


@implementation USAePayCustomerObject
@synthesize Amount;
@synthesize BillingAddress;
@synthesize Created;
@synthesize Currency;
@synthesize CustNum;
@synthesize CustomData;
@synthesize CustomFields;
@synthesize CustomerID;
@synthesize Description;
@synthesize Enabled;
@synthesize Failures;
@synthesize LookupCode;
@synthesize Modified;
@synthesize Next;
@synthesize Notes;
@synthesize NumLeft;
@synthesize OrderID;
@synthesize PaymentMethods;
@synthesize PriceTier;
@synthesize ReceiptNote;
@synthesize Schedule;
@synthesize SendReceipt;
@synthesize Source;
@synthesize Tax;
@synthesize TaxClass;
@synthesize User;
@synthesize URL;
@synthesize any;

+ (USAePayCustomerObject *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.Amount =[NSNumber numberWithInt:0];
        self.CustomFields =[[USAePayFieldValueArray alloc]init];
        self.NumLeft =[NSNumber numberWithInt:0];
        self.PaymentMethods =[[USAePayPaymentMethodArray alloc]init];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"Amount"])
                 {
                     if([USAePayHelper isValue:__node name:@"Amount"])
                     {
                         self.Amount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"BillingAddress"])
                 {
                     if([USAePayHelper isValue:__node name:@"BillingAddress"])
                     {
                         self.BillingAddress = (USAePayAddress*)[__request createObject:__node type:[USAePayAddress class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Created"])
                 {
                     if([USAePayHelper isValue:__node name:@"Created"])
                     {
                         self.Created = [USAePayHelper getDate:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Currency"])
                 {
                     if([USAePayHelper isValue:__node name:@"Currency"])
                     {
                         self.Currency = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustNum"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustNum"])
                     {
                         self.CustNum = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustomData"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustomData"])
                     {
                         self.CustomData = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustomFields"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustomFields"])
                     {
                         self.CustomFields = (USAePayFieldValueArray*)[__request createObject:__node type:[USAePayFieldValueArray class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CustomerID"])
                 {
                     if([USAePayHelper isValue:__node name:@"CustomerID"])
                     {
                         self.CustomerID = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Description"])
                 {
                     if([USAePayHelper isValue:__node name:@"Description"])
                     {
                         self.Description = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Enabled"])
                 {
                     if([USAePayHelper isValue:__node name:@"Enabled"])
                     {
                         self.Enabled = [[__node stringValue] boolValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Failures"])
                 {
                     if([USAePayHelper isValue:__node name:@"Failures"])
                     {
                         self.Failures = [NSNumber numberWithInt:[[__node stringValue] intValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"LookupCode"])
                 {
                     if([USAePayHelper isValue:__node name:@"LookupCode"])
                     {
                         self.LookupCode = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Modified"])
                 {
                     if([USAePayHelper isValue:__node name:@"Modified"])
                     {
                         self.Modified = [USAePayHelper getDate:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Next"])
                 {
                     if([USAePayHelper isValue:__node name:@"Next"])
                     {
                         self.Next = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Notes"])
                 {
                     if([USAePayHelper isValue:__node name:@"Notes"])
                     {
                         self.Notes = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"NumLeft"])
                 {
                     if([USAePayHelper isValue:__node name:@"NumLeft"])
                     {
                         self.NumLeft = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"OrderID"])
                 {
                     if([USAePayHelper isValue:__node name:@"OrderID"])
                     {
                         self.OrderID = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"PaymentMethods"])
                 {
                     if([USAePayHelper isValue:__node name:@"PaymentMethods"])
                     {
                         self.PaymentMethods = (USAePayPaymentMethodArray*)[__request createObject:__node type:[USAePayPaymentMethodArray class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"PriceTier"])
                 {
                     if([USAePayHelper isValue:__node name:@"PriceTier"])
                     {
                         self.PriceTier = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ReceiptNote"])
                 {
                     if([USAePayHelper isValue:__node name:@"ReceiptNote"])
                     {
                         self.ReceiptNote = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Schedule"])
                 {
                     if([USAePayHelper isValue:__node name:@"Schedule"])
                     {
                         self.Schedule = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"SendReceipt"])
                 {
                     if([USAePayHelper isValue:__node name:@"SendReceipt"])
                     {
                         self.SendReceipt = [[__node stringValue] boolValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Source"])
                 {
                     if([USAePayHelper isValue:__node name:@"Source"])
                     {
                         self.Source = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Tax"])
                 {
                     if([USAePayHelper isValue:__node name:@"Tax"])
                     {
                         self.Tax = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"TaxClass"])
                 {
                     if([USAePayHelper isValue:__node name:@"TaxClass"])
                     {
                         self.TaxClass = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"User"])
                 {
                     if([USAePayHelper isValue:__node name:@"User"])
                     {
                         self.User = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"URL"])
                 {
                     if([USAePayHelper isValue:__node name:@"URL"])
                     {
                         self.URL = [__node stringValue];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __AmountItemElement=[__request writeElement:Amount type:[NSNumber class] name:@"Amount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__AmountItemElement!=nil)
    {
        [__AmountItemElement setStringValue:[self.Amount stringValue]];
    }
            
    DDXMLElement* __BillingAddressItemElement=[__request writeElement:BillingAddress type:[USAePayAddress class] name:@"BillingAddress" URI:@"" parent:__parent skipNullProperty:NO];
    if(__BillingAddressItemElement!=nil)
    {
        [self.BillingAddress serialize:__BillingAddressItemElement __request: __request];
    }
            
    DDXMLElement* __CreatedItemElement=[__request writeElement:Created type:[NSDate class] name:@"Created" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CreatedItemElement!=nil)
    {
        [__CreatedItemElement setStringValue:[USAePayHelper getStringFromDateTime:self.Created]];
    }
            
    DDXMLElement* __CurrencyItemElement=[__request writeElement:Currency type:[NSString class] name:@"Currency" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CurrencyItemElement!=nil)
    {
        [__CurrencyItemElement setStringValue:self.Currency];
    }
            
    DDXMLElement* __CustNumItemElement=[__request writeElement:CustNum type:[NSString class] name:@"CustNum" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CustNumItemElement!=nil)
    {
        [__CustNumItemElement setStringValue:self.CustNum];
    }
            
    DDXMLElement* __CustomDataItemElement=[__request writeElement:CustomData type:[NSString class] name:@"CustomData" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CustomDataItemElement!=nil)
    {
        [__CustomDataItemElement setStringValue:self.CustomData];
    }
            
    DDXMLElement* __CustomFieldsItemElement=[__request writeElement:CustomFields type:[USAePayFieldValueArray class] name:@"CustomFields" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CustomFieldsItemElement!=nil)
    {
        [self.CustomFields serialize:__CustomFieldsItemElement __request: __request];
    }
            
    DDXMLElement* __CustomerIDItemElement=[__request writeElement:CustomerID type:[NSString class] name:@"CustomerID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CustomerIDItemElement!=nil)
    {
        [__CustomerIDItemElement setStringValue:self.CustomerID];
    }
            
    DDXMLElement* __DescriptionItemElement=[__request writeElement:Description type:[NSString class] name:@"Description" URI:@"" parent:__parent skipNullProperty:NO];
    if(__DescriptionItemElement!=nil)
    {
        [__DescriptionItemElement setStringValue:self.Description];
    }
            
    DDXMLElement* __EnabledItemElement=[__request writeElement:@"Enabled" URI:@"" parent:__parent];
    [__EnabledItemElement setStringValue:[USAePayHelper toBoolStringFromBool:self.Enabled]];
            
    DDXMLElement* __FailuresItemElement=[__request writeElement:Failures type:[NSNumber class] name:@"Failures" URI:@"" parent:__parent skipNullProperty:YES];
    if(__FailuresItemElement!=nil)
    {
        [__FailuresItemElement setStringValue:[self.Failures stringValue]];
    }
            
    DDXMLElement* __LookupCodeItemElement=[__request writeElement:LookupCode type:[NSString class] name:@"LookupCode" URI:@"" parent:__parent skipNullProperty:YES];
    if(__LookupCodeItemElement!=nil)
    {
        [__LookupCodeItemElement setStringValue:self.LookupCode];
    }
            
    DDXMLElement* __ModifiedItemElement=[__request writeElement:Modified type:[NSDate class] name:@"Modified" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ModifiedItemElement!=nil)
    {
        [__ModifiedItemElement setStringValue:[USAePayHelper getStringFromDateTime:self.Modified]];
    }
            
    DDXMLElement* __NextItemElement=[__request writeElement:Next type:[NSString class] name:@"Next" URI:@"" parent:__parent skipNullProperty:NO];
    if(__NextItemElement!=nil)
    {
        [__NextItemElement setStringValue:self.Next];
    }
            
    DDXMLElement* __NotesItemElement=[__request writeElement:Notes type:[NSString class] name:@"Notes" URI:@"" parent:__parent skipNullProperty:YES];
    if(__NotesItemElement!=nil)
    {
        [__NotesItemElement setStringValue:self.Notes];
    }
            
    DDXMLElement* __NumLeftItemElement=[__request writeElement:NumLeft type:[NSNumber class] name:@"NumLeft" URI:@"" parent:__parent skipNullProperty:NO];
    if(__NumLeftItemElement!=nil)
    {
        [__NumLeftItemElement setStringValue:[self.NumLeft stringValue]];
    }
            
    DDXMLElement* __OrderIDItemElement=[__request writeElement:OrderID type:[NSString class] name:@"OrderID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__OrderIDItemElement!=nil)
    {
        [__OrderIDItemElement setStringValue:self.OrderID];
    }
            
    DDXMLElement* __PaymentMethodsItemElement=[__request writeElement:PaymentMethods type:[USAePayPaymentMethodArray class] name:@"PaymentMethods" URI:@"" parent:__parent skipNullProperty:YES];
    if(__PaymentMethodsItemElement!=nil)
    {
        [self.PaymentMethods serialize:__PaymentMethodsItemElement __request: __request];
    }
            
    DDXMLElement* __PriceTierItemElement=[__request writeElement:PriceTier type:[NSString class] name:@"PriceTier" URI:@"" parent:__parent skipNullProperty:YES];
    if(__PriceTierItemElement!=nil)
    {
        [__PriceTierItemElement setStringValue:self.PriceTier];
    }
            
    DDXMLElement* __ReceiptNoteItemElement=[__request writeElement:ReceiptNote type:[NSString class] name:@"ReceiptNote" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ReceiptNoteItemElement!=nil)
    {
        [__ReceiptNoteItemElement setStringValue:self.ReceiptNote];
    }
            
    DDXMLElement* __ScheduleItemElement=[__request writeElement:Schedule type:[NSString class] name:@"Schedule" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ScheduleItemElement!=nil)
    {
        [__ScheduleItemElement setStringValue:self.Schedule];
    }
            
    DDXMLElement* __SendReceiptItemElement=[__request writeElement:@"SendReceipt" URI:@"" parent:__parent];
    [__SendReceiptItemElement setStringValue:[USAePayHelper toBoolStringFromBool:self.SendReceipt]];
            
    DDXMLElement* __SourceItemElement=[__request writeElement:Source type:[NSString class] name:@"Source" URI:@"" parent:__parent skipNullProperty:YES];
    if(__SourceItemElement!=nil)
    {
        [__SourceItemElement setStringValue:self.Source];
    }
            
    DDXMLElement* __TaxItemElement=[__request writeElement:Tax type:[NSNumber class] name:@"Tax" URI:@"" parent:__parent skipNullProperty:YES];
    if(__TaxItemElement!=nil)
    {
        [__TaxItemElement setStringValue:[self.Tax stringValue]];
    }
            
    DDXMLElement* __TaxClassItemElement=[__request writeElement:TaxClass type:[NSString class] name:@"TaxClass" URI:@"" parent:__parent skipNullProperty:YES];
    if(__TaxClassItemElement!=nil)
    {
        [__TaxClassItemElement setStringValue:self.TaxClass];
    }
            
    DDXMLElement* __UserItemElement=[__request writeElement:User type:[NSString class] name:@"User" URI:@"" parent:__parent skipNullProperty:YES];
    if(__UserItemElement!=nil)
    {
        [__UserItemElement setStringValue:self.User];
    }
            
    DDXMLElement* __URLItemElement=[__request writeElement:URL type:[NSString class] name:@"URL" URI:@"" parent:__parent skipNullProperty:YES];
    if(__URLItemElement!=nil)
    {
        [__URLItemElement setStringValue:self.URL];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
