//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayBatchStatusArray.h"
#import "USAePayHelper.h"
#import "USAePayBatchSearchResult.h"


@implementation USAePayBatchSearchResult
@synthesize Batches;
@synthesize BatchesMatched;
@synthesize BatchesReturned;
@synthesize Limit;
@synthesize StartIndex;
@synthesize any;

+ (USAePayBatchSearchResult *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.Batches =[[USAePayBatchStatusArray alloc]init];
        self.BatchesMatched =[NSNumber numberWithInt:0];
        self.BatchesReturned =[NSNumber numberWithInt:0];
        self.Limit =[NSNumber numberWithInt:0];
        self.StartIndex =[NSNumber numberWithInt:0];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"Batches"])
                 {
                     if([USAePayHelper isValue:__node name:@"Batches"])
                     {
                         self.Batches = (USAePayBatchStatusArray*)[__request createObject:__node type:[USAePayBatchStatusArray class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"BatchesMatched"])
                 {
                     if([USAePayHelper isValue:__node name:@"BatchesMatched"])
                     {
                         self.BatchesMatched = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"BatchesReturned"])
                 {
                     if([USAePayHelper isValue:__node name:@"BatchesReturned"])
                     {
                         self.BatchesReturned = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Limit"])
                 {
                     if([USAePayHelper isValue:__node name:@"Limit"])
                     {
                         self.Limit = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"StartIndex"])
                 {
                     if([USAePayHelper isValue:__node name:@"StartIndex"])
                     {
                         self.StartIndex = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __BatchesItemElement=[__request writeElement:Batches type:[USAePayBatchStatusArray class] name:@"Batches" URI:@"" parent:__parent skipNullProperty:NO];
    if(__BatchesItemElement!=nil)
    {
        [self.Batches serialize:__BatchesItemElement __request: __request];
    }
            
    DDXMLElement* __BatchesMatchedItemElement=[__request writeElement:BatchesMatched type:[NSNumber class] name:@"BatchesMatched" URI:@"" parent:__parent skipNullProperty:NO];
    if(__BatchesMatchedItemElement!=nil)
    {
        [__BatchesMatchedItemElement setStringValue:[self.BatchesMatched stringValue]];
    }
            
    DDXMLElement* __BatchesReturnedItemElement=[__request writeElement:BatchesReturned type:[NSNumber class] name:@"BatchesReturned" URI:@"" parent:__parent skipNullProperty:NO];
    if(__BatchesReturnedItemElement!=nil)
    {
        [__BatchesReturnedItemElement setStringValue:[self.BatchesReturned stringValue]];
    }
            
    DDXMLElement* __LimitItemElement=[__request writeElement:Limit type:[NSNumber class] name:@"Limit" URI:@"" parent:__parent skipNullProperty:NO];
    if(__LimitItemElement!=nil)
    {
        [__LimitItemElement setStringValue:[self.Limit stringValue]];
    }
            
    DDXMLElement* __StartIndexItemElement=[__request writeElement:StartIndex type:[NSNumber class] name:@"StartIndex" URI:@"" parent:__parent skipNullProperty:NO];
    if(__StartIndexItemElement!=nil)
    {
        [__StartIndexItemElement setStringValue:[self.StartIndex stringValue]];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
