//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class USAePayHelper;
#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayRecurringBilling : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getAmount) NSNumber* Amount;

@property (nonatomic,getter=getEnabled) BOOL Enabled;

@property (retain,nonatomic,getter=getExpire) NSString* Expire;

@property (retain,nonatomic,getter=getNext) NSString* Next;

@property (retain,nonatomic,getter=getNumLeft) NSNumber* NumLeft;

@property (retain,nonatomic,getter=getSchedule) NSString* Schedule;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayRecurringBilling*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end