//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class USAePayFieldValueArray;
@class USAePayTransactionDetail;
@class USAePayLineItemArray;
#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayCustomerTransactionRequest : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getCommand) NSString* Command;

@property (retain,nonatomic,getter=getCardCode) NSString* CardCode;

@property (retain,nonatomic,getter=getClientIP) NSString* ClientIP;

@property (retain,nonatomic,getter=getCustomFields) USAePayFieldValueArray* CustomFields;

@property (retain,nonatomic,getter=getCustReceipt) NSNumber* CustReceipt;

@property (retain,nonatomic,getter=getCustReceiptEmail) NSString* CustReceiptEmail;

@property (retain,nonatomic,getter=getCustReceiptName) NSString* CustReceiptName;

@property (retain,nonatomic,getter=getMerchReceipt) NSNumber* MerchReceipt;

@property (retain,nonatomic,getter=getMerchReceiptEmail) NSString* MerchReceiptEmail;

@property (retain,nonatomic,getter=getMerchReceiptName) NSString* MerchReceiptName;

@property (retain,nonatomic,getter=getDetails) USAePayTransactionDetail* Details;

@property (retain,nonatomic,getter=getIgnoreDuplicate) NSNumber* IgnoreDuplicate;

@property (retain,nonatomic,getter=getIsRecurring) NSNumber* isRecurring;

@property (retain,nonatomic,getter=getLineItems) USAePayLineItemArray* LineItems;

@property (retain,nonatomic,getter=getSoftware) NSString* Software;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayCustomerTransactionRequest*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end