//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePayBatchStatus.h"


@implementation USAePayBatchStatus
@synthesize BatchRefNum;
@synthesize Closed;
@synthesize CreditsAmount;
@synthesize CreditsCount;
@synthesize NetAmount;
@synthesize Opened;
@synthesize SalesAmount;
@synthesize SalesCount;
@synthesize Scheduled;
@synthesize Sequence;
@synthesize Status;
@synthesize TransactionCount;
@synthesize VoidsAmount;
@synthesize VoidsCount;
@synthesize any;

+ (USAePayBatchStatus *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.BatchRefNum =[NSNumber numberWithInt:0];
        self.CreditsAmount =[NSNumber numberWithInt:0];
        self.CreditsCount =[NSNumber numberWithInt:0];
        self.NetAmount =[NSNumber numberWithInt:0];
        self.SalesAmount =[NSNumber numberWithInt:0];
        self.SalesCount =[NSNumber numberWithInt:0];
        self.Sequence =[NSNumber numberWithInt:0];
        self.TransactionCount =[NSNumber numberWithInt:0];
        self.VoidsAmount =[NSNumber numberWithInt:0];
        self.VoidsCount =[NSNumber numberWithInt:0];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"BatchRefNum"])
                 {
                     if([USAePayHelper isValue:__node name:@"BatchRefNum"])
                     {
                         self.BatchRefNum = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Closed"])
                 {
                     if([USAePayHelper isValue:__node name:@"Closed"])
                     {
                         self.Closed = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CreditsAmount"])
                 {
                     if([USAePayHelper isValue:__node name:@"CreditsAmount"])
                     {
                         self.CreditsAmount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CreditsCount"])
                 {
                     if([USAePayHelper isValue:__node name:@"CreditsCount"])
                     {
                         self.CreditsCount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"NetAmount"])
                 {
                     if([USAePayHelper isValue:__node name:@"NetAmount"])
                     {
                         self.NetAmount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Opened"])
                 {
                     if([USAePayHelper isValue:__node name:@"Opened"])
                     {
                         self.Opened = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"SalesAmount"])
                 {
                     if([USAePayHelper isValue:__node name:@"SalesAmount"])
                     {
                         self.SalesAmount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"SalesCount"])
                 {
                     if([USAePayHelper isValue:__node name:@"SalesCount"])
                     {
                         self.SalesCount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Scheduled"])
                 {
                     if([USAePayHelper isValue:__node name:@"Scheduled"])
                     {
                         self.Scheduled = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Sequence"])
                 {
                     if([USAePayHelper isValue:__node name:@"Sequence"])
                     {
                         self.Sequence = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Status"])
                 {
                     if([USAePayHelper isValue:__node name:@"Status"])
                     {
                         self.Status = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"TransactionCount"])
                 {
                     if([USAePayHelper isValue:__node name:@"TransactionCount"])
                     {
                         self.TransactionCount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"VoidsAmount"])
                 {
                     if([USAePayHelper isValue:__node name:@"VoidsAmount"])
                     {
                         self.VoidsAmount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"VoidsCount"])
                 {
                     if([USAePayHelper isValue:__node name:@"VoidsCount"])
                     {
                         self.VoidsCount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __BatchRefNumItemElement=[__request writeElement:BatchRefNum type:[NSNumber class] name:@"BatchRefNum" URI:@"" parent:__parent skipNullProperty:NO];
    if(__BatchRefNumItemElement!=nil)
    {
        [__BatchRefNumItemElement setStringValue:[self.BatchRefNum stringValue]];
    }
            
    DDXMLElement* __ClosedItemElement=[__request writeElement:Closed type:[NSString class] name:@"Closed" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ClosedItemElement!=nil)
    {
        [__ClosedItemElement setStringValue:self.Closed];
    }
            
    DDXMLElement* __CreditsAmountItemElement=[__request writeElement:CreditsAmount type:[NSNumber class] name:@"CreditsAmount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CreditsAmountItemElement!=nil)
    {
        [__CreditsAmountItemElement setStringValue:[self.CreditsAmount stringValue]];
    }
            
    DDXMLElement* __CreditsCountItemElement=[__request writeElement:CreditsCount type:[NSNumber class] name:@"CreditsCount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CreditsCountItemElement!=nil)
    {
        [__CreditsCountItemElement setStringValue:[self.CreditsCount stringValue]];
    }
            
    DDXMLElement* __NetAmountItemElement=[__request writeElement:NetAmount type:[NSNumber class] name:@"NetAmount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__NetAmountItemElement!=nil)
    {
        [__NetAmountItemElement setStringValue:[self.NetAmount stringValue]];
    }
            
    DDXMLElement* __OpenedItemElement=[__request writeElement:Opened type:[NSString class] name:@"Opened" URI:@"" parent:__parent skipNullProperty:NO];
    if(__OpenedItemElement!=nil)
    {
        [__OpenedItemElement setStringValue:self.Opened];
    }
            
    DDXMLElement* __SalesAmountItemElement=[__request writeElement:SalesAmount type:[NSNumber class] name:@"SalesAmount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__SalesAmountItemElement!=nil)
    {
        [__SalesAmountItemElement setStringValue:[self.SalesAmount stringValue]];
    }
            
    DDXMLElement* __SalesCountItemElement=[__request writeElement:SalesCount type:[NSNumber class] name:@"SalesCount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__SalesCountItemElement!=nil)
    {
        [__SalesCountItemElement setStringValue:[self.SalesCount stringValue]];
    }
            
    DDXMLElement* __ScheduledItemElement=[__request writeElement:Scheduled type:[NSString class] name:@"Scheduled" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ScheduledItemElement!=nil)
    {
        [__ScheduledItemElement setStringValue:self.Scheduled];
    }
            
    DDXMLElement* __SequenceItemElement=[__request writeElement:Sequence type:[NSNumber class] name:@"Sequence" URI:@"" parent:__parent skipNullProperty:NO];
    if(__SequenceItemElement!=nil)
    {
        [__SequenceItemElement setStringValue:[self.Sequence stringValue]];
    }
            
    DDXMLElement* __StatusItemElement=[__request writeElement:Status type:[NSString class] name:@"Status" URI:@"" parent:__parent skipNullProperty:NO];
    if(__StatusItemElement!=nil)
    {
        [__StatusItemElement setStringValue:self.Status];
    }
            
    DDXMLElement* __TransactionCountItemElement=[__request writeElement:TransactionCount type:[NSNumber class] name:@"TransactionCount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TransactionCountItemElement!=nil)
    {
        [__TransactionCountItemElement setStringValue:[self.TransactionCount stringValue]];
    }
            
    DDXMLElement* __VoidsAmountItemElement=[__request writeElement:VoidsAmount type:[NSNumber class] name:@"VoidsAmount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VoidsAmountItemElement!=nil)
    {
        [__VoidsAmountItemElement setStringValue:[self.VoidsAmount stringValue]];
    }
            
    DDXMLElement* __VoidsCountItemElement=[__request writeElement:VoidsCount type:[NSNumber class] name:@"VoidsCount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VoidsCountItemElement!=nil)
    {
        [__VoidsCountItemElement setStringValue:[self.VoidsCount stringValue]];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
