//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePayBank.h"


@implementation USAePayBank
@synthesize Code;
@synthesize Name;
@synthesize any;

+ (USAePayBank *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"Code"])
                 {
                     if([USAePayHelper isValue:__node name:@"Code"])
                     {
                         self.Code = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Name"])
                 {
                     if([USAePayHelper isValue:__node name:@"Name"])
                     {
                         self.Name = [__node stringValue];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __CodeItemElement=[__request writeElement:Code type:[NSString class] name:@"Code" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CodeItemElement!=nil)
    {
        [__CodeItemElement setStringValue:self.Code];
    }
            
    DDXMLElement* __NameItemElement=[__request writeElement:Name type:[NSString class] name:@"Name" URI:@"" parent:__parent skipNullProperty:NO];
    if(__NameItemElement!=nil)
    {
        [__NameItemElement setStringValue:self.Name];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
