//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePayProductInventoryArray.h"
#import "USAePayPriceTierArray.h"
#import "USAePayProduct.h"


@implementation USAePayProduct
@synthesize ProductRefNum;
@synthesize ProductID;
@synthesize SKU;
@synthesize UPC;
@synthesize Category;
@synthesize Enabled;
@synthesize Name;
@synthesize Description;
@synthesize Model;
@synthesize Weight;
@synthesize ShipWeight;
@synthesize Price;
@synthesize WholesalePrice;
@synthesize ListPrice;
@synthesize DateAvailable;
@synthesize Manufacturer;
@synthesize PhysicalGood;
@synthesize TaxClass;
@synthesize MinQuantity;
@synthesize ImageURL;
@synthesize URL;
@synthesize Created;
@synthesize Modified;
@synthesize Inventory;
@synthesize PriceTiers;
@synthesize any;

+ (USAePayProduct *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.Price =[NSNumber numberWithInt:0];
        self.Inventory =[[USAePayProductInventoryArray alloc]init];
        self.PriceTiers =[[USAePayPriceTierArray alloc]init];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"ProductRefNum"])
                 {
                     if([USAePayHelper isValue:__node name:@"ProductRefNum"])
                     {
                         self.ProductRefNum = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ProductID"])
                 {
                     if([USAePayHelper isValue:__node name:@"ProductID"])
                     {
                         self.ProductID = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"SKU"])
                 {
                     if([USAePayHelper isValue:__node name:@"SKU"])
                     {
                         self.SKU = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"UPC"])
                 {
                     if([USAePayHelper isValue:__node name:@"UPC"])
                     {
                         self.UPC = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Category"])
                 {
                     if([USAePayHelper isValue:__node name:@"Category"])
                     {
                         self.Category = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Enabled"])
                 {
                     if([USAePayHelper isValue:__node name:@"Enabled"])
                     {
                         self.Enabled = [[NSNumber alloc]initWithBool:[[__node stringValue] boolValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Name"])
                 {
                     if([USAePayHelper isValue:__node name:@"Name"])
                     {
                         self.Name = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Description"])
                 {
                     if([USAePayHelper isValue:__node name:@"Description"])
                     {
                         self.Description = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Model"])
                 {
                     if([USAePayHelper isValue:__node name:@"Model"])
                     {
                         self.Model = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Weight"])
                 {
                     if([USAePayHelper isValue:__node name:@"Weight"])
                     {
                         self.Weight = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ShipWeight"])
                 {
                     if([USAePayHelper isValue:__node name:@"ShipWeight"])
                     {
                         self.ShipWeight = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Price"])
                 {
                     if([USAePayHelper isValue:__node name:@"Price"])
                     {
                         self.Price = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"WholesalePrice"])
                 {
                     if([USAePayHelper isValue:__node name:@"WholesalePrice"])
                     {
                         self.WholesalePrice = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ListPrice"])
                 {
                     if([USAePayHelper isValue:__node name:@"ListPrice"])
                     {
                         self.ListPrice = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"DateAvailable"])
                 {
                     if([USAePayHelper isValue:__node name:@"DateAvailable"])
                     {
                         self.DateAvailable = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Manufacturer"])
                 {
                     if([USAePayHelper isValue:__node name:@"Manufacturer"])
                     {
                         self.Manufacturer = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"PhysicalGood"])
                 {
                     if([USAePayHelper isValue:__node name:@"PhysicalGood"])
                     {
                         self.PhysicalGood = [[NSNumber alloc]initWithBool:[[__node stringValue] boolValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"TaxClass"])
                 {
                     if([USAePayHelper isValue:__node name:@"TaxClass"])
                     {
                         self.TaxClass = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"MinQuantity"])
                 {
                     if([USAePayHelper isValue:__node name:@"MinQuantity"])
                     {
                         self.MinQuantity = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ImageURL"])
                 {
                     if([USAePayHelper isValue:__node name:@"ImageURL"])
                     {
                         self.ImageURL = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"URL"])
                 {
                     if([USAePayHelper isValue:__node name:@"URL"])
                     {
                         self.URL = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Created"])
                 {
                     if([USAePayHelper isValue:__node name:@"Created"])
                     {
                         self.Created = [USAePayHelper getDate:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Modified"])
                 {
                     if([USAePayHelper isValue:__node name:@"Modified"])
                     {
                         self.Modified = [USAePayHelper getDate:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Inventory"])
                 {
                     if([USAePayHelper isValue:__node name:@"Inventory"])
                     {
                         self.Inventory = (USAePayProductInventoryArray*)[__request createObject:__node type:[USAePayProductInventoryArray class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"PriceTiers"])
                 {
                     if([USAePayHelper isValue:__node name:@"PriceTiers"])
                     {
                         self.PriceTiers = (USAePayPriceTierArray*)[__request createObject:__node type:[USAePayPriceTierArray class]];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __ProductRefNumItemElement=[__request writeElement:ProductRefNum type:[NSString class] name:@"ProductRefNum" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ProductRefNumItemElement!=nil)
    {
        [__ProductRefNumItemElement setStringValue:self.ProductRefNum];
    }
            
    DDXMLElement* __ProductIDItemElement=[__request writeElement:ProductID type:[NSString class] name:@"ProductID" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ProductIDItemElement!=nil)
    {
        [__ProductIDItemElement setStringValue:self.ProductID];
    }
            
    DDXMLElement* __SKUItemElement=[__request writeElement:SKU type:[NSString class] name:@"SKU" URI:@"" parent:__parent skipNullProperty:YES];
    if(__SKUItemElement!=nil)
    {
        [__SKUItemElement setStringValue:self.SKU];
    }
            
    DDXMLElement* __UPCItemElement=[__request writeElement:UPC type:[NSString class] name:@"UPC" URI:@"" parent:__parent skipNullProperty:YES];
    if(__UPCItemElement!=nil)
    {
        [__UPCItemElement setStringValue:self.UPC];
    }
            
    DDXMLElement* __CategoryItemElement=[__request writeElement:Category type:[NSString class] name:@"Category" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CategoryItemElement!=nil)
    {
        [__CategoryItemElement setStringValue:self.Category];
    }
            
    DDXMLElement* __EnabledItemElement=[__request writeElement:Enabled type:[NSNumber class] name:@"Enabled" URI:@"" parent:__parent skipNullProperty:YES];
    if(__EnabledItemElement!=nil)
    {
        [__EnabledItemElement setStringValue:[USAePayHelper toBoolStringFromNumber:self.Enabled]];
    }
            
    DDXMLElement* __NameItemElement=[__request writeElement:Name type:[NSString class] name:@"Name" URI:@"" parent:__parent skipNullProperty:NO];
    if(__NameItemElement!=nil)
    {
        [__NameItemElement setStringValue:self.Name];
    }
            
    DDXMLElement* __DescriptionItemElement=[__request writeElement:Description type:[NSString class] name:@"Description" URI:@"" parent:__parent skipNullProperty:YES];
    if(__DescriptionItemElement!=nil)
    {
        [__DescriptionItemElement setStringValue:self.Description];
    }
            
    DDXMLElement* __ModelItemElement=[__request writeElement:Model type:[NSString class] name:@"Model" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ModelItemElement!=nil)
    {
        [__ModelItemElement setStringValue:self.Model];
    }
            
    DDXMLElement* __WeightItemElement=[__request writeElement:Weight type:[NSNumber class] name:@"Weight" URI:@"" parent:__parent skipNullProperty:YES];
    if(__WeightItemElement!=nil)
    {
        [__WeightItemElement setStringValue:[self.Weight stringValue]];
    }
            
    DDXMLElement* __ShipWeightItemElement=[__request writeElement:ShipWeight type:[NSNumber class] name:@"ShipWeight" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ShipWeightItemElement!=nil)
    {
        [__ShipWeightItemElement setStringValue:[self.ShipWeight stringValue]];
    }
            
    DDXMLElement* __PriceItemElement=[__request writeElement:Price type:[NSNumber class] name:@"Price" URI:@"" parent:__parent skipNullProperty:NO];
    if(__PriceItemElement!=nil)
    {
        [__PriceItemElement setStringValue:[self.Price stringValue]];
    }
            
    DDXMLElement* __WholesalePriceItemElement=[__request writeElement:WholesalePrice type:[NSNumber class] name:@"WholesalePrice" URI:@"" parent:__parent skipNullProperty:YES];
    if(__WholesalePriceItemElement!=nil)
    {
        [__WholesalePriceItemElement setStringValue:[self.WholesalePrice stringValue]];
    }
            
    DDXMLElement* __ListPriceItemElement=[__request writeElement:ListPrice type:[NSNumber class] name:@"ListPrice" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ListPriceItemElement!=nil)
    {
        [__ListPriceItemElement setStringValue:[self.ListPrice stringValue]];
    }
            
    DDXMLElement* __DateAvailableItemElement=[__request writeElement:DateAvailable type:[NSString class] name:@"DateAvailable" URI:@"" parent:__parent skipNullProperty:YES];
    if(__DateAvailableItemElement!=nil)
    {
        [__DateAvailableItemElement setStringValue:self.DateAvailable];
    }
            
    DDXMLElement* __ManufacturerItemElement=[__request writeElement:Manufacturer type:[NSString class] name:@"Manufacturer" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ManufacturerItemElement!=nil)
    {
        [__ManufacturerItemElement setStringValue:self.Manufacturer];
    }
            
    DDXMLElement* __PhysicalGoodItemElement=[__request writeElement:PhysicalGood type:[NSNumber class] name:@"PhysicalGood" URI:@"" parent:__parent skipNullProperty:YES];
    if(__PhysicalGoodItemElement!=nil)
    {
        [__PhysicalGoodItemElement setStringValue:[USAePayHelper toBoolStringFromNumber:self.PhysicalGood]];
    }
            
    DDXMLElement* __TaxClassItemElement=[__request writeElement:TaxClass type:[NSString class] name:@"TaxClass" URI:@"" parent:__parent skipNullProperty:YES];
    if(__TaxClassItemElement!=nil)
    {
        [__TaxClassItemElement setStringValue:self.TaxClass];
    }
            
    DDXMLElement* __MinQuantityItemElement=[__request writeElement:MinQuantity type:[NSNumber class] name:@"MinQuantity" URI:@"" parent:__parent skipNullProperty:YES];
    if(__MinQuantityItemElement!=nil)
    {
        [__MinQuantityItemElement setStringValue:[self.MinQuantity stringValue]];
    }
            
    DDXMLElement* __ImageURLItemElement=[__request writeElement:ImageURL type:[NSString class] name:@"ImageURL" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ImageURLItemElement!=nil)
    {
        [__ImageURLItemElement setStringValue:self.ImageURL];
    }
            
    DDXMLElement* __URLItemElement=[__request writeElement:URL type:[NSString class] name:@"URL" URI:@"" parent:__parent skipNullProperty:YES];
    if(__URLItemElement!=nil)
    {
        [__URLItemElement setStringValue:self.URL];
    }
            
    DDXMLElement* __CreatedItemElement=[__request writeElement:Created type:[NSDate class] name:@"Created" URI:@"" parent:__parent skipNullProperty:YES];
    if(__CreatedItemElement!=nil)
    {
        [__CreatedItemElement setStringValue:[USAePayHelper getStringFromDateTime:self.Created]];
    }
            
    DDXMLElement* __ModifiedItemElement=[__request writeElement:Modified type:[NSDate class] name:@"Modified" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ModifiedItemElement!=nil)
    {
        [__ModifiedItemElement setStringValue:[USAePayHelper getStringFromDateTime:self.Modified]];
    }
            
    DDXMLElement* __InventoryItemElement=[__request writeElement:Inventory type:[USAePayProductInventoryArray class] name:@"Inventory" URI:@"" parent:__parent skipNullProperty:YES];
    if(__InventoryItemElement!=nil)
    {
        [self.Inventory serialize:__InventoryItemElement __request: __request];
    }
            
    DDXMLElement* __PriceTiersItemElement=[__request writeElement:PriceTiers type:[USAePayPriceTierArray class] name:@"PriceTiers" URI:@"" parent:__parent skipNullProperty:YES];
    if(__PriceTiersItemElement!=nil)
    {
        [self.PriceTiers serialize:__PriceTiersItemElement __request: __request];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
