//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePayCurrencyConversion.h"


@implementation USAePayCurrencyConversion
@synthesize Amount;
@synthesize Currency;
@synthesize FromAmount;
@synthesize FromCurrency;
@synthesize Rate;
@synthesize any;

+ (USAePayCurrencyConversion *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.Amount =[NSNumber numberWithInt:0];
        self.FromAmount =[NSNumber numberWithInt:0];
        self.Rate =[NSNumber numberWithInt:0];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"Amount"])
                 {
                     if([USAePayHelper isValue:__node name:@"Amount"])
                     {
                         self.Amount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Currency"])
                 {
                     if([USAePayHelper isValue:__node name:@"Currency"])
                     {
                         self.Currency = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"FromAmount"])
                 {
                     if([USAePayHelper isValue:__node name:@"FromAmount"])
                     {
                         self.FromAmount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"FromCurrency"])
                 {
                     if([USAePayHelper isValue:__node name:@"FromCurrency"])
                     {
                         self.FromCurrency = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Rate"])
                 {
                     if([USAePayHelper isValue:__node name:@"Rate"])
                     {
                         self.Rate = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __AmountItemElement=[__request writeElement:Amount type:[NSNumber class] name:@"Amount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__AmountItemElement!=nil)
    {
        [__AmountItemElement setStringValue:[self.Amount stringValue]];
    }
            
    DDXMLElement* __CurrencyItemElement=[__request writeElement:Currency type:[NSString class] name:@"Currency" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CurrencyItemElement!=nil)
    {
        [__CurrencyItemElement setStringValue:self.Currency];
    }
            
    DDXMLElement* __FromAmountItemElement=[__request writeElement:FromAmount type:[NSNumber class] name:@"FromAmount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__FromAmountItemElement!=nil)
    {
        [__FromAmountItemElement setStringValue:[self.FromAmount stringValue]];
    }
            
    DDXMLElement* __FromCurrencyItemElement=[__request writeElement:FromCurrency type:[NSString class] name:@"FromCurrency" URI:@"" parent:__parent skipNullProperty:NO];
    if(__FromCurrencyItemElement!=nil)
    {
        [__FromCurrencyItemElement setStringValue:self.FromCurrency];
    }
            
    DDXMLElement* __RateItemElement=[__request writeElement:Rate type:[NSNumber class] name:@"Rate" URI:@"" parent:__parent skipNullProperty:NO];
    if(__RateItemElement!=nil)
    {
        [__RateItemElement setStringValue:[self.Rate stringValue]];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
