//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class USAePayCurrencyObjectArray;
#import "USAePayRequestResultHandler.h"
#import "DDXML.h"



@interface USAePayAccountDetails : NSObject <USAePayISerializableObject>


@property (retain,nonatomic,getter=getCardholderAuthentication) NSString* CardholderAuthentication;

@property (retain,nonatomic,getter=getCheckPlatform) NSString* CheckPlatform;

@property (retain,nonatomic,getter=getCreditCardPlatform) NSString* CreditCardPlatform;

@property (nonatomic,getter=getDebitCardSupport) BOOL DebitCardSupport;

@property (retain,nonatomic,getter=getDirectPayPlatform) NSString* DirectPayPlatform;

@property (retain,nonatomic,getter=getIndustry) NSString* Industry;

@property (retain,nonatomic,getter=getSupportedCurrencies) USAePayCurrencyObjectArray* SupportedCurrencies;

@property (retain,nonatomic,getter=getAny) NSMutableArray* any;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
+(USAePayAccountDetails*) createWithXml:(DDXMLElement*)__node __request:(USAePayRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request;
@end