//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePayBatchUploadStatus.h"


@implementation USAePayBatchUploadStatus
@synthesize Approved;
@synthesize UploadRefNum;
@synthesize Declined;
@synthesize Errors;
@synthesize Finished;
@synthesize Remaining;
@synthesize Started;
@synthesize Status;
@synthesize Transactions;
@synthesize any;

+ (USAePayBatchUploadStatus *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.Approved =[NSNumber numberWithInt:0];
        self.UploadRefNum =[NSNumber numberWithInt:0];
        self.Declined =[NSNumber numberWithInt:0];
        self.Errors =[NSNumber numberWithInt:0];
        self.Remaining =[NSNumber numberWithInt:0];
        self.Transactions =[NSNumber numberWithInt:0];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"Approved"])
                 {
                     if([USAePayHelper isValue:__node name:@"Approved"])
                     {
                         self.Approved = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"UploadRefNum"])
                 {
                     if([USAePayHelper isValue:__node name:@"UploadRefNum"])
                     {
                         self.UploadRefNum = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Declined"])
                 {
                     if([USAePayHelper isValue:__node name:@"Declined"])
                     {
                         self.Declined = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Errors"])
                 {
                     if([USAePayHelper isValue:__node name:@"Errors"])
                     {
                         self.Errors = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Finished"])
                 {
                     if([USAePayHelper isValue:__node name:@"Finished"])
                     {
                         self.Finished = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Remaining"])
                 {
                     if([USAePayHelper isValue:__node name:@"Remaining"])
                     {
                         self.Remaining = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Started"])
                 {
                     if([USAePayHelper isValue:__node name:@"Started"])
                     {
                         self.Started = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Status"])
                 {
                     if([USAePayHelper isValue:__node name:@"Status"])
                     {
                         self.Status = [__node stringValue];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Transactions"])
                 {
                     if([USAePayHelper isValue:__node name:@"Transactions"])
                     {
                         self.Transactions = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __ApprovedItemElement=[__request writeElement:Approved type:[NSNumber class] name:@"Approved" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ApprovedItemElement!=nil)
    {
        [__ApprovedItemElement setStringValue:[self.Approved stringValue]];
    }
            
    DDXMLElement* __UploadRefNumItemElement=[__request writeElement:UploadRefNum type:[NSNumber class] name:@"UploadRefNum" URI:@"" parent:__parent skipNullProperty:NO];
    if(__UploadRefNumItemElement!=nil)
    {
        [__UploadRefNumItemElement setStringValue:[self.UploadRefNum stringValue]];
    }
            
    DDXMLElement* __DeclinedItemElement=[__request writeElement:Declined type:[NSNumber class] name:@"Declined" URI:@"" parent:__parent skipNullProperty:NO];
    if(__DeclinedItemElement!=nil)
    {
        [__DeclinedItemElement setStringValue:[self.Declined stringValue]];
    }
            
    DDXMLElement* __ErrorsItemElement=[__request writeElement:Errors type:[NSNumber class] name:@"Errors" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ErrorsItemElement!=nil)
    {
        [__ErrorsItemElement setStringValue:[self.Errors stringValue]];
    }
            
    DDXMLElement* __FinishedItemElement=[__request writeElement:Finished type:[NSString class] name:@"Finished" URI:@"" parent:__parent skipNullProperty:NO];
    if(__FinishedItemElement!=nil)
    {
        [__FinishedItemElement setStringValue:self.Finished];
    }
            
    DDXMLElement* __RemainingItemElement=[__request writeElement:Remaining type:[NSNumber class] name:@"Remaining" URI:@"" parent:__parent skipNullProperty:NO];
    if(__RemainingItemElement!=nil)
    {
        [__RemainingItemElement setStringValue:[self.Remaining stringValue]];
    }
            
    DDXMLElement* __StartedItemElement=[__request writeElement:Started type:[NSString class] name:@"Started" URI:@"" parent:__parent skipNullProperty:NO];
    if(__StartedItemElement!=nil)
    {
        [__StartedItemElement setStringValue:self.Started];
    }
            
    DDXMLElement* __StatusItemElement=[__request writeElement:Status type:[NSString class] name:@"Status" URI:@"" parent:__parent skipNullProperty:NO];
    if(__StatusItemElement!=nil)
    {
        [__StatusItemElement setStringValue:self.Status];
    }
            
    DDXMLElement* __TransactionsItemElement=[__request writeElement:Transactions type:[NSNumber class] name:@"Transactions" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TransactionsItemElement!=nil)
    {
        [__TransactionsItemElement setStringValue:[self.Transactions stringValue]];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
