//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.9.0
//
// Created by Quasar Development at 02-11-2015
//
//---------------------------------------------------


#import "USAePayHelper.h"
#import "USAePayTransactionObjectArray.h"
#import "USAePayTransactionSearchResult.h"


@implementation USAePayTransactionSearchResult
@synthesize AuthOnlyAmount;
@synthesize AuthOnlyCount;
@synthesize CreditsAmount;
@synthesize CreditsCount;
@synthesize DeclinesAmount;
@synthesize DeclinesCount;
@synthesize ErrorsAmount;
@synthesize ErrorsCount;
@synthesize Limit;
@synthesize SalesAmount;
@synthesize SalesCount;
@synthesize StartIndex;
@synthesize Transactions;
@synthesize TransactionsMatched;
@synthesize TransactionsReturned;
@synthesize VoidsAmount;
@synthesize VoidsCount;
@synthesize any;

+ (USAePayTransactionSearchResult *)createWithXml:(DDXMLElement *)__node __request:(USAePayRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.AuthOnlyAmount =[NSNumber numberWithInt:0];
        self.AuthOnlyCount =[NSNumber numberWithInt:0];
        self.CreditsAmount =[NSNumber numberWithInt:0];
        self.CreditsCount =[NSNumber numberWithInt:0];
        self.DeclinesAmount =[NSNumber numberWithInt:0];
        self.DeclinesCount =[NSNumber numberWithInt:0];
        self.ErrorsAmount =[NSNumber numberWithInt:0];
        self.ErrorsCount =[NSNumber numberWithInt:0];
        self.Limit =[NSNumber numberWithInt:0];
        self.SalesAmount =[NSNumber numberWithInt:0];
        self.SalesCount =[NSNumber numberWithInt:0];
        self.StartIndex =[NSNumber numberWithInt:0];
        self.Transactions =[[USAePayTransactionObjectArray alloc]init];
        self.TransactionsMatched =[NSNumber numberWithInt:0];
        self.TransactionsReturned =[NSNumber numberWithInt:0];
        self.VoidsAmount =[NSNumber numberWithInt:0];
        self.VoidsCount =[NSNumber numberWithInt:0];
        self.any =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(USAePayRequestResultHandler*) __request{
    if(self = [self init])
    {
        DDXMLNode* node=__node;
        for(int i=0;i< node.childCount;i++)
        {
            DDXMLNode* node=[__node childAtIndex:i];
            if(node.kind==DDXMLElementKind)
            {
                DDXMLElement* __node=(DDXMLElement*)node;
                 if([__node.localName isEqualToString:@"AuthOnlyAmount"])
                 {
                     if([USAePayHelper isValue:__node name:@"AuthOnlyAmount"])
                     {
                         self.AuthOnlyAmount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"AuthOnlyCount"])
                 {
                     if([USAePayHelper isValue:__node name:@"AuthOnlyCount"])
                     {
                         self.AuthOnlyCount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CreditsAmount"])
                 {
                     if([USAePayHelper isValue:__node name:@"CreditsAmount"])
                     {
                         self.CreditsAmount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"CreditsCount"])
                 {
                     if([USAePayHelper isValue:__node name:@"CreditsCount"])
                     {
                         self.CreditsCount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"DeclinesAmount"])
                 {
                     if([USAePayHelper isValue:__node name:@"DeclinesAmount"])
                     {
                         self.DeclinesAmount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"DeclinesCount"])
                 {
                     if([USAePayHelper isValue:__node name:@"DeclinesCount"])
                     {
                         self.DeclinesCount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ErrorsAmount"])
                 {
                     if([USAePayHelper isValue:__node name:@"ErrorsAmount"])
                     {
                         self.ErrorsAmount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"ErrorsCount"])
                 {
                     if([USAePayHelper isValue:__node name:@"ErrorsCount"])
                     {
                         self.ErrorsCount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Limit"])
                 {
                     if([USAePayHelper isValue:__node name:@"Limit"])
                     {
                         self.Limit = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"SalesAmount"])
                 {
                     if([USAePayHelper isValue:__node name:@"SalesAmount"])
                     {
                         self.SalesAmount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"SalesCount"])
                 {
                     if([USAePayHelper isValue:__node name:@"SalesCount"])
                     {
                         self.SalesCount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"StartIndex"])
                 {
                     if([USAePayHelper isValue:__node name:@"StartIndex"])
                     {
                         self.StartIndex = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"Transactions"])
                 {
                     if([USAePayHelper isValue:__node name:@"Transactions"])
                     {
                         self.Transactions = (USAePayTransactionObjectArray*)[__request createObject:__node type:[USAePayTransactionObjectArray class]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"TransactionsMatched"])
                 {
                     if([USAePayHelper isValue:__node name:@"TransactionsMatched"])
                     {
                         self.TransactionsMatched = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"TransactionsReturned"])
                 {
                     if([USAePayHelper isValue:__node name:@"TransactionsReturned"])
                     {
                         self.TransactionsReturned = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"VoidsAmount"])
                 {
                     if([USAePayHelper isValue:__node name:@"VoidsAmount"])
                     {
                         self.VoidsAmount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
                 if([__node.localName isEqualToString:@"VoidsCount"])
                 {
                     if([USAePayHelper isValue:__node name:@"VoidsCount"])
                     {
                         self.VoidsCount = [USAePayHelper getNumber:[__node stringValue]];
                     }
                     continue;
                 }
               [self.any addObject:__node];
            }
         }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(USAePayRequestResultHandler*) __request
{

            
    DDXMLElement* __AuthOnlyAmountItemElement=[__request writeElement:AuthOnlyAmount type:[NSNumber class] name:@"AuthOnlyAmount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__AuthOnlyAmountItemElement!=nil)
    {
        [__AuthOnlyAmountItemElement setStringValue:[self.AuthOnlyAmount stringValue]];
    }
            
    DDXMLElement* __AuthOnlyCountItemElement=[__request writeElement:AuthOnlyCount type:[NSNumber class] name:@"AuthOnlyCount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__AuthOnlyCountItemElement!=nil)
    {
        [__AuthOnlyCountItemElement setStringValue:[self.AuthOnlyCount stringValue]];
    }
            
    DDXMLElement* __CreditsAmountItemElement=[__request writeElement:CreditsAmount type:[NSNumber class] name:@"CreditsAmount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CreditsAmountItemElement!=nil)
    {
        [__CreditsAmountItemElement setStringValue:[self.CreditsAmount stringValue]];
    }
            
    DDXMLElement* __CreditsCountItemElement=[__request writeElement:CreditsCount type:[NSNumber class] name:@"CreditsCount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__CreditsCountItemElement!=nil)
    {
        [__CreditsCountItemElement setStringValue:[self.CreditsCount stringValue]];
    }
            
    DDXMLElement* __DeclinesAmountItemElement=[__request writeElement:DeclinesAmount type:[NSNumber class] name:@"DeclinesAmount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__DeclinesAmountItemElement!=nil)
    {
        [__DeclinesAmountItemElement setStringValue:[self.DeclinesAmount stringValue]];
    }
            
    DDXMLElement* __DeclinesCountItemElement=[__request writeElement:DeclinesCount type:[NSNumber class] name:@"DeclinesCount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__DeclinesCountItemElement!=nil)
    {
        [__DeclinesCountItemElement setStringValue:[self.DeclinesCount stringValue]];
    }
            
    DDXMLElement* __ErrorsAmountItemElement=[__request writeElement:ErrorsAmount type:[NSNumber class] name:@"ErrorsAmount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ErrorsAmountItemElement!=nil)
    {
        [__ErrorsAmountItemElement setStringValue:[self.ErrorsAmount stringValue]];
    }
            
    DDXMLElement* __ErrorsCountItemElement=[__request writeElement:ErrorsCount type:[NSNumber class] name:@"ErrorsCount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__ErrorsCountItemElement!=nil)
    {
        [__ErrorsCountItemElement setStringValue:[self.ErrorsCount stringValue]];
    }
            
    DDXMLElement* __LimitItemElement=[__request writeElement:Limit type:[NSNumber class] name:@"Limit" URI:@"" parent:__parent skipNullProperty:NO];
    if(__LimitItemElement!=nil)
    {
        [__LimitItemElement setStringValue:[self.Limit stringValue]];
    }
            
    DDXMLElement* __SalesAmountItemElement=[__request writeElement:SalesAmount type:[NSNumber class] name:@"SalesAmount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__SalesAmountItemElement!=nil)
    {
        [__SalesAmountItemElement setStringValue:[self.SalesAmount stringValue]];
    }
            
    DDXMLElement* __SalesCountItemElement=[__request writeElement:SalesCount type:[NSNumber class] name:@"SalesCount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__SalesCountItemElement!=nil)
    {
        [__SalesCountItemElement setStringValue:[self.SalesCount stringValue]];
    }
            
    DDXMLElement* __StartIndexItemElement=[__request writeElement:StartIndex type:[NSNumber class] name:@"StartIndex" URI:@"" parent:__parent skipNullProperty:NO];
    if(__StartIndexItemElement!=nil)
    {
        [__StartIndexItemElement setStringValue:[self.StartIndex stringValue]];
    }
            
    DDXMLElement* __TransactionsItemElement=[__request writeElement:Transactions type:[USAePayTransactionObjectArray class] name:@"Transactions" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TransactionsItemElement!=nil)
    {
        [self.Transactions serialize:__TransactionsItemElement __request: __request];
    }
            
    DDXMLElement* __TransactionsMatchedItemElement=[__request writeElement:TransactionsMatched type:[NSNumber class] name:@"TransactionsMatched" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TransactionsMatchedItemElement!=nil)
    {
        [__TransactionsMatchedItemElement setStringValue:[self.TransactionsMatched stringValue]];
    }
            
    DDXMLElement* __TransactionsReturnedItemElement=[__request writeElement:TransactionsReturned type:[NSNumber class] name:@"TransactionsReturned" URI:@"" parent:__parent skipNullProperty:NO];
    if(__TransactionsReturnedItemElement!=nil)
    {
        [__TransactionsReturnedItemElement setStringValue:[self.TransactionsReturned stringValue]];
    }
            
    DDXMLElement* __VoidsAmountItemElement=[__request writeElement:VoidsAmount type:[NSNumber class] name:@"VoidsAmount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VoidsAmountItemElement!=nil)
    {
        [__VoidsAmountItemElement setStringValue:[self.VoidsAmount stringValue]];
    }
            
    DDXMLElement* __VoidsCountItemElement=[__request writeElement:VoidsCount type:[NSNumber class] name:@"VoidsCount" URI:@"" parent:__parent skipNullProperty:NO];
    if(__VoidsCountItemElement!=nil)
    {
        [__VoidsCountItemElement setStringValue:[self.VoidsCount stringValue]];
    }
            
    for(DDXMLElement* elem in self.any)
    {
        [elem detach];
        [__parent addChild:elem];
    }


}
@end
