//
//  MIMEKit.h
//  MIMEKit
//
//  Created by Jeff Hay on 4/15/12.
//  Copyright (c) 2012 Portable Knowledge, LLC. All rights reserved.
//

#import <Foundation/Foundation.h>

#import "PKMIMEData.h"
#import "PKMIMEMessage.h"
#import "PKMIMEMessage+XOP-XML.h"

#if (TARGET_IPHONE_SIMULATOR) || (TARGET_OS_IPHONE)
#import "UIImage+MIME.h"
#endif

#import "NSData+GUID.h"
#import "NSString+GUID.h"

#import "NSData+MIMETransferEncoding.h"
#import "NSData+Base64.h"

#import "NSDictionary+CaseInsensitiveKeys.h"

/**
 * MIME is Multipurpose Internet Mail Extensions, a standard for encoding and transmitting data over computer 
 * communication networks.  While oringally defined as a format for sending rich email content, MIME has been adapted for 
 * a variety of communication needs, including several HTTP request/response messaging patterns.
 *
 * The MIMEKit Framework provides a native Objective-C implementation for working with MIME messages as defined by RFCs
 * [2045](http://tools.ietf.org/html/rfc2045), [2046](http://tools.ietf.org/html/rfc2046), [2047](http://tools.ietf.org/html/rfc2047), 
 * and [2049](http://tools.ietf.org/html/rfc2049).   MIMEKit also supports reading and writing 
 * [XOP+XML](http://www.w3.org/TR/xop10/) and [MTOM](http://www.w3.org/TR/soap12-mtom/) messages for working with SOAP-based 
 * web services applications.
 *
 * `MIMEKit` supports all defined MIME encoding standards, including pure binary, base64, and quoted-printable.  For base64 
 * encoding, `MIMEKit` makes use of Mattt Gallagher's excellent 
 * [NSData+Base64](http://cocoawithlove.com/2009/06/base64-encoding-options-on-mac-and.html) category, which is included in 
 * the `MIMEKit` source tree.  
 *
 * To get started with `MIMEKit`, look at the documentation for PKMIMEMessage and PKMIMEData, in particular the class methods.
 * To translate between MIME messages and images, see the static methods in `UIImage+MIME`.
 *
 * `MIMEKit` was originally developed by [Portable Knowledge, LLC](http://www.portablek.com) and is released 
 * to the public under the Portable Knowledge Open Source Component License as it appears below.  This license  
 * is a very permissive open-source license adapted from the Boost Software License and should be fully
 * GPL and FSF compatible.
 *
 * In short:
 *
 *  * Anyone is free to use and modify this software for any use, private or commercial, provided
 *    the original copyright and license text are maintained in any distributed source code.
 *
 *  * Portable Knowledge, LLC assumes no liability for use of this software
 *
 *  * No warranty of any kind is provided for this software
 *
 *  * Portable Knowledge, LLC assumes no responsibility to update or maintain this software in the future,
 *    and releases it to the public "as-is"
 *
 *  * In no case does the use of this software by others imply any partnership or endorsement
 *    by Portable Knowledge, LLC
 *
 * We hope this library is of use to the iPhone and MacOS development community!  Please use and share
 * as you see fit.  All the code is documented via in-line comments compatible with 
 * [appledoc](https://github.com/tomaz/appledoc) and [doxygen](http://www.stack.nl/~dimitri/doxygen/), 
 * either of which can be used to create documentation sets for XCode or standalone HTML pages.  A shell
 * script is provided to compile documentation and install it into XCode using appledoc.
 *
 * >**Portable Knowledge Open Source Component License - Version 1.0 - April 13th, 2012**
 * 
 * >`Permission is hereby granted, free of charge, to any person or organization` 
 * >`obtaining a copy of the software and accompanying documentation covered by`
 * >`this license (the "Software") to use, reproduce, display, distribute,`
 * >`execute, and transmit the Software, and to prepare derivative works of the`
 * >`Software, and to permit third-parties to whom the Software is furnished to`
 * >`do so, all subject to the following:`
 * 
 * >`The copyright notices in the Software and this entire statement, including`
 * >`the above license grant, this restriction and the following disclaimer,`
 * >`must be included in all copies of the Software, in whole or in part, and`
 * >`all derivative works of the Software, unless such copies or derivative`
 * >`works are solely in the form of machine-executable object code generated by`
 * >`a source language processor.`
 * 
 * >`THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR`
 * >`IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,`
 * >`FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT`
 * >`SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE`
 * >`FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,`
 * >`ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER`
 * >`DEALINGS IN THE SOFTWARE.  IN NO CASE DOES THE USE OF THIS SOFTWARE EXPRESS`
 * >`OR IMPLY ANY PARTNERSHIP OR COOPERATION WITH THE AUTHORS OR COPYRIGHT HOLDERS`
 * >`OF THIS SOFTWARE.`
 **/

@interface MIMEKit : NSObject

@end
